// apps/frontend-next/src/components/layout/Navigation.tsx
// ===== TMFashion Navigation Component =====
// Thanh điều hướng chính (tương đương components/layout/Navigation.vue)
// Logo TMF 60px + nav links + search bar với sticker + cart + auth

"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useEffect, useRef } from "react";
import { useAuthStore } from "@/stores/auth";
import { useCartStore } from "@/stores/cart";
import { api } from "@/lib/api";

interface SearchProduct {
  _id: string;
  name: string;
  image_url?: string;
  price: number;
}

export default function Navigation() {
  const router = useRouter();
  const { user, isLoggedIn, isAdmin, logout } = useAuthStore();
  const cartStore = useCartStore();

  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState<SearchProduct[]>([]);
  const [showSearch, setShowSearch] = useState(false);
  const [showUserMenu, setShowUserMenu] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const searchRef = useRef<HTMLDivElement>(null);
  const userMenuRef = useRef<HTMLDivElement>(null);

  // Init auth on mount
  useEffect(() => {
    useAuthStore.getState().init();
  }, []);

  // Fetch cart khi đã đăng nhập
  useEffect(() => {
    if (isLoggedIn) {
      cartStore.fetchCart();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoggedIn]);

  // Close menus on click outside
  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (searchRef.current && !searchRef.current.contains(e.target as Node)) {
        setShowSearch(false);
      }
      if (userMenuRef.current && !userMenuRef.current.contains(e.target as Node)) {
        setShowUserMenu(false);
      }
    }
    document.addEventListener("click", handleClickOutside);
    return () => document.removeEventListener("click", handleClickOutside);
  }, []);

  // Search autocomplete
  useEffect(() => {
    if (searchQuery.length < 2) {
      setSearchResults([]);
      setShowSearch(false);
      return;
    }
    const timer = setTimeout(async () => {
      try {
        const data = await api.get<{ data: SearchProduct[]; pagination: any }>("/products", {
          keyword: searchQuery,
          limit: 5,
        });
        setSearchResults(data.data || []);
        setShowSearch(true);
      } catch {
        /* ignore */
      }
    }, 300);
    return () => clearTimeout(timer);
  }, [searchQuery]);

  function handleLogout() {
    logout();
    router.push("/");
  }

  function handleSearchSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (searchQuery.trim()) {
      router.push(`/shop?q=${encodeURIComponent(searchQuery)}`);
      setShowSearch(false);
    }
  }

  return (
    <nav className="bg-white sticky top-0 z-50 shadow-sm">
      <div className="max-w-[1200px] mx-auto px-4">
        <div className="flex items-center justify-between h-[70px]">
          {/* Logo TMF — giống Nuxt: font-Longreach 60px */}
          <Link href="/" className="flex-shrink-0">
            <span className="text-[48px] lg:text-[60px] text-primary font-[var(--font-longreach)] leading-none">
              TMF
            </span>
          </Link>

          {/* Nav Links (Desktop) — giống Nuxt: Trang chủ, Danh mục, Giới thiệu, Tạp chí */}
          <div className="hidden md:flex items-center gap-5 ml-6">
            <Link href="/" className="text-[14px] text-gray-tmf hover:text-primary transition font-medium">
              Trang chủ
            </Link>
            <Link href="/shop" className="text-[14px] text-gray-tmf hover:text-primary transition font-medium">
              Danh mục
            </Link>
            <Link href="/fitting-room" className="text-[14px] text-gray-tmf hover:text-primary transition font-medium">
              Phòng thử đồ
            </Link>
            <Link href="/introduce" className="text-[14px] text-gray-tmf hover:text-primary transition font-medium">
              Giới thiệu
            </Link>
          </div>

          {/* Search Bar — giống Nuxt: border-2 border-primary rounded-[12px] + sticker */}
          <div className="flex-1 max-w-[328px] mx-4 relative" ref={searchRef}>
            <form onSubmit={handleSearchSubmit} className="relative">
              {/* Sticker image on left — giống Nuxt icon_thanhsearch.png */}
              <img
                src="/icon_thanhsearch.png"
                alt=""
                className="absolute left-[-12px] top-1/2 -translate-y-1/2 w-[40px] h-[40px] z-10 pointer-events-none"
              />
              <input
                type="text"
                placeholder="Tìm kiếm sản phẩm..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-10 pr-10 py-[8px] border-2 border-primary rounded-[12px] text-[13px] focus:outline-none focus:ring-1 focus:ring-primary bg-white"
              />
              <button
                type="submit"
                className="absolute right-3 top-1/2 -translate-y-1/2"
              >
                <svg
                  className="h-[18px] w-[18px] text-primary"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                  />
                </svg>
              </button>
            </form>

            {/* Autocomplete dropdown */}
            {showSearch && searchResults.length > 0 && (
              <div className="absolute top-full left-0 right-0 bg-white border-2 border-primary rounded-[12px] shadow-lg mt-1 z-50 overflow-hidden">
                {searchResults.map((p) => (
                  <Link
                    key={p._id}
                    href={`/p/${p._id}`}
                    className="flex items-center gap-3 px-4 py-3 hover:bg-gray-50 transition"
                    onClick={() => setShowSearch(false)}
                  >
                    <img
                      src={p.image_url || "/placeholder.png"}
                      alt={p.name}
                      className="w-10 h-10 object-cover rounded"
                    />
                    <span className="text-[13px] text-gray-700 line-clamp-1">
                      {p.name}
                    </span>
                  </Link>
                ))}
              </div>
            )}
          </div>

          {/* Right Side: Cart + User — giống Nuxt */}
          <div className="flex items-center gap-3">
            {/* Cart icon */}
            <Link href="/checkout" className="relative p-2 text-gray-tmf hover:text-primary transition">
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"
                />
              </svg>
              {cartStore.totalItems > 0 && (
                <span className="absolute -top-1 -right-1 bg-red-500 text-white text-[10px] font-bold rounded-full w-5 h-5 flex items-center justify-center">
                  {cartStore.totalItems}
                </span>
              )}
            </Link>

            {/* User Menu */}
            {isLoggedIn ? (
              <div className="relative" ref={userMenuRef}>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setShowUserMenu(!showUserMenu);
                  }}
                  className="flex items-center gap-2 p-2 text-gray-tmf hover:text-primary transition"
                >
                  <div className="w-8 h-8 bg-primary rounded-full flex items-center justify-center text-[13px] font-bold text-white">
                    {user?.fullName?.charAt(0) || "U"}
                  </div>
                  <span className="hidden lg:block text-[13px] font-medium text-gray-tmf">
                    {user?.fullName || "User"}
                  </span>
                </button>

                {showUserMenu && (
                  <div className="absolute right-0 top-full mt-2 w-48 bg-white border rounded-lg shadow-lg z-50">
                    <Link
                      href="/account"
                      className="block px-4 py-3 text-[13px] text-gray-700 hover:bg-gray-50 transition"
                    >
                      Tài khoản
                    </Link>
                    <Link
                      href="/account/orders"
                      className="block px-4 py-3 text-[13px] text-gray-700 hover:bg-gray-50 transition"
                    >
                      Đơn hàng
                    </Link>
                    {isAdmin && (
                      <Link
                        href="/admin"
                        className="block px-4 py-3 text-[13px] text-gray-700 hover:bg-gray-50 transition"
                      >
                        Quản trị
                      </Link>
                    )}
                    <button
                      onClick={handleLogout}
                      className="w-full text-left px-4 py-3 text-[13px] text-red-500 hover:bg-gray-50 border-t transition"
                    >
                      Đăng xuất
                    </button>
                  </div>
                )}
              </div>
            ) : (
              <div className="hidden sm:flex items-center gap-2 text-[13px]">
                <Link
                  href="/login"
                  className="text-gray-tmf hover:text-primary transition font-medium"
                >
                  Đăng nhập
                </Link>
                <span className="text-gray-300">|</span>
                <Link
                  href="/register"
                  className="text-gray-tmf hover:text-primary transition font-medium"
                >
                  Đăng ký
                </Link>
              </div>
            )}

            {/* Mobile Menu Button */}
            <button
              className="md:hidden p-2"
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            >
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d={mobileMenuOpen ? "M6 18L18 6M6 6l12 12" : "M4 6h16M4 12h16M4 18h16"}
                />
              </svg>
            </button>
          </div>
        </div>

        {/* Mobile Menu */}
        {mobileMenuOpen && (
          <div className="md:hidden border-t py-4 space-y-2">
            <Link href="/" className="block px-4 py-2 text-gray-700 hover:bg-gray-50 rounded">
              Trang chủ
            </Link>
            <Link href="/shop" className="block px-4 py-2 text-gray-700 hover:bg-gray-50 rounded">
              Danh mục
            </Link>
            <Link href="/fitting-room" className="block px-4 py-2 text-gray-700 hover:bg-gray-50 rounded">
              Phòng thử đồ
            </Link>
            <Link href="/introduce" className="block px-4 py-2 text-gray-700 hover:bg-gray-50 rounded">
              Giới thiệu
            </Link>
          </div>
        )}
      </div>
    </nav>
  );
}

// frontend-nuxt/components/layout/Navigation.vue
<template>
  <nav>
    <Wrap attr3="flexRow-between w-full">
      <div class="flex items-center gap-[24px]">
        <NuxtLink :to="localePath(`/`)">
          <span class="font-Longreach text-[60px] font-normal text-grayTMF">
            TMF
          </span>
        </NuxtLink>
        <button
          v-for="item in itemHeader"
          :key="item.name"
          :class="
            getSegment(fullURL, 0) === item.slug ? 'gap-[10px] border-b-[4px] border-primary' : ''
          "
        >
          <NuxtLink :to="localePath(item.link)">
            <span
              class="font-monasans text-[16px] leading-[160%] text-grayTMF"
              :class="getSegment(fullURL, 0) === item.slug ? 'font-bold' : 'font-normal'"
            >
              {{ item.name }}
            </span>
          </NuxtLink>
        </button>
      </div>

      <div class="flex gap-[20px] items-center">
        <div
          class="w-[500px] lg:w-[328px] search-container relative mr-[12px] h-[48px] rounded-[12px] border-[2px] border-primary bg-white transition-all duration-300"
        >
          <div class="absolute left-0 top-0 h-full w-[60px] overflow-hidden rounded-l-[12px]">
            <img
              :src="Sticker"
              alt="Ảnh thanh search"
              class="h-[160px] w-[62px] object-cover"
            >
          </div>

          <input
            v-model="searchQuery"
            type="text"
            placeholder="Tìm Hoddie cho mùa đông"
            class="absolute left-[61px] top-[10px] w-[75%] text-[16px] leading-[160%] text-grayTMF focus:outline-none"
            @input="handleSearch"
            @keydown.enter="submitSearch"
            @focus="showDropdown = true"
          >

          <!-- Search Icon Button -->
          <button
            @click="submitSearch"
            class="absolute right-3 top-1/2 -translate-y-1/2 text-grayTMF hover:text-gray-900"
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
          </button>

          <!-- Dropdown Autocomplete -->
          <div
            v-if="showDropdown && (searchResults.length > 0 || searchLoading)"
            class="absolute top-full left-0 right-0 mt-2 bg-white border-2 border-primary rounded-lg shadow-lg max-h-[400px] overflow-y-auto z-50"
          >
            <!-- Loading -->
            <div v-if="searchLoading" class="p-4 text-center text-gray-500">
              Đang tìm kiếm...
            </div>

            <!-- Results -->
            <div v-else-if="searchResults.length > 0" class="py-2">
              <NuxtLink
                v-for="product in searchResults"
                :key="product.id"
                :to="`/p/${product.slug || product.id}`"
                class="flex items-center gap-3 px-4 py-3 hover:bg-gray-100 transition"
                @click="closeDropdown"
              >
                <img
                  :src="product.imageUrl || '/placeholder.png'"
                  :alt="product.name"
                  class="w-12 h-12 object-cover rounded"
                >
                <div class="flex-1">
                  <p class="font-medium text-grayTMF">{{ product.name }}</p>
                  <p class="text-sm text-gray-500">{{ formatPrice(product.price) }}</p>
                </div>
              </NuxtLink>
            </div>

            <!-- No Results -->
            <div v-else class="p-4 text-center text-gray-500">
              Không tìm thấy sản phẩm
            </div>
          </div>
        </div>

        <!-- Cart Icon -->
        <NuxtLink
          to="/cart"
          class="relative p-2 hover:bg-gray-100 rounded-full transition"
        >
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-grayTMF" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
          </svg>
          <!-- Badge số lượng -->
          <span
            v-if="cartStore.totalItems > 0"
            class="absolute -top-1 -right-1 bg-red-500 text-white text-xs font-bold rounded-full h-5 w-5 flex items-center justify-center"
          >
            {{ cartStore.totalItems > 99 ? '99+' : cartStore.totalItems }}
          </span>
        </NuxtLink>

        <!-- User Menu - Login/Logout -->
        <div class="flex items-center gap-3">
          <!-- Đã đăng nhập -->
          <template v-if="authStore.isLoggedIn">
            <!-- Link tài khoản -->
            <NuxtLink
              to="/account"
              class="flex items-center gap-2 text-sm text-grayTMF hover:text-gray-900 transition"
            >
              <div class="w-8 h-8 bg-primary rounded-full flex items-center justify-center">
                <span class="text-sm font-bold text-gray-800">
                  {{ userInitial }}
                </span>
              </div>
              <span class="hidden lg:block">
                <strong>{{ authStore.user?.fullName || authStore.user?.email }}</strong>
              </span>
            </NuxtLink>

            <!-- Nút vào Admin (chỉ hiện với ADMIN) -->
            <NuxtLink
              v-if="authStore.isAdmin"
              to="/admin"
              class="px-3 py-1.5 text-sm bg-primary hover:bg-yellow-500 text-gray-800 rounded-lg transition font-medium"
            >
              Admin
            </NuxtLink>

            <!-- Nút Đăng xuất -->
            <button
              class="px-3 py-1.5 text-sm bg-gray-200 hover:bg-gray-300 text-gray-700 rounded-lg transition"
              @click="handleLogout"
            >
              Đăng xuất
            </button>
          </template>

          <!-- Chưa đăng nhập -->
          <template v-else>
            <NuxtLink
              to="/login"
              class="px-4 py-2 text-sm bg-primary hover:bg-yellow-500 text-gray-800 font-medium rounded-lg transition"
            >
              Đăng nhập
            </NuxtLink>
            <NuxtLink
              to="/register"
              class="px-4 py-2 text-sm bg-gray-200 hover:bg-gray-300 text-gray-700 rounded-lg transition"
            >
              Đăng ký
            </NuxtLink>
          </template>
        </div>

        <!-- <LanguageSwitcher /> -->
      </div>

    </Wrap>
  </nav>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useI18n, useLocalePath, useRoute, useRouter } from '#imports'
import { useCartStore } from '~/store/cart'
import { useAuthStore } from '~/store/auth'

const { t } = useI18n()
const localePath = useLocalePath()
const route = useRoute()
const router = useRouter()
const fullURL = computed(() => route.fullPath)
const cartStore = useCartStore()
const authStore = useAuthStore()
const config = useRuntimeConfig()

// Search state
const searchQuery = ref('')
const searchResults = ref<any[]>([])
const searchLoading = ref(false)
const showDropdown = ref(false)
let searchTimeout: NodeJS.Timeout | null = null

// Fetch cart khi đã login
onMounted(() => {
  if (authStore.isLoggedIn) {
    cartStore.fetchCart()
  }

  // Close dropdown when clicking outside
  document.addEventListener('click', handleClickOutside)
})

onBeforeUnmount(() => {
  document.removeEventListener('click', handleClickOutside)
  if (searchTimeout) clearTimeout(searchTimeout)
})

function handleClickOutside(event: MouseEvent) {
  const target = event.target as HTMLElement
  if (!target.closest('.search-container')) {
    showDropdown.value = false
  }
}

// Debounced search
async function handleSearch() {
  if (searchTimeout) clearTimeout(searchTimeout)

  if (!searchQuery.value.trim()) {
    searchResults.value = []
    showDropdown.value = false
    return
  }

  searchLoading.value = true
  showDropdown.value = true

  searchTimeout = setTimeout(async () => {
    try {
      const response = await $fetch<any>(`${config.public.apiBase}/products`, {
        params: {
          q: searchQuery.value,
          pageSize: 8
        }
      })
      searchResults.value = response.items || []
    } catch (error) {
      console.error('Search error:', error)
      searchResults.value = []
    } finally {
      searchLoading.value = false
    }
  }, 300)
}

// Submit search (navigate to products page)
function submitSearch() {
  if (searchQuery.value.trim()) {
    closeDropdown()
    router.push({
      path: '/shop',
      query: { q: searchQuery.value }
    })
  }
}

function closeDropdown() {
  showDropdown.value = false
}

function formatPrice(price: number) {
  return new Intl.NumberFormat('vi-VN', {
    style: 'currency',
    currency: 'VND'
  }).format(price)
}

// Helper function to get URL segment
function getSegment(url: string, index: number) {
  const segments = url.split('/').filter(s => s)
  return segments[index] || ''
}

// Watch login state để fetch cart
watch(() => authStore.isLoggedIn, (isLoggedIn) => {
  if (isLoggedIn) {
    cartStore.fetchCart()
  } else {
    cartStore.clearCart()
  }
})

// Logout handler
function handleLogout() {
  authStore.logout()
  cartStore.clearCart()
}

// User initial for avatar
const userInitial = computed(() => {
  const name = authStore.user?.fullName || authStore.user?.email || 'U'
  return name.charAt(0).toUpperCase()
})

const itemHeader = computed(() => [
  {
    name: t('nav.home'),
    link: localePath(`/`),
    slug: ``,
  },
  {
    name: t('nav.categories'),
    link: localePath(`/category/ao`),
    slug: 'category',
  },
  {
    name: t('nav.about'),
    link: localePath(`/introduce`),
    slug: 'introduce',
  },
  {
    name: t('nav.blog'),
    link: localePath(`/blog`),
    slug: 'blog',
  },
])

const Sticker = '/icon_thanhsearch.png'
</script>

<style scoped>
.slide-up-enter-active,
.slide-up-leave-active {
  transition:
    transform 0.3s ease,
    opacity 0.3s ease;
  will-change: transform, opacity;
}

.slide-up-enter-from,
.slide-up-leave-to {
  transform: translateY(-100%);
  opacity: 0;
}

.slide-up-enter-to,
.slide-up-leave-from {
  transform: translateY(0);
  opacity: 1;
}
</style>
