// apps/frontend-next/src/app/admin/orders/page.tsx
// ===== TMFashion Admin Orders Page =====
// Tương đương pages/admin/orders.vue
// SD: Quản lý đơn hàng → Admin duyệt/cập nhật đơn
// STM Quản lý đơn hàng: Xem danh sách → Lọc theo trạng thái → Cập nhật trạng thái

"use client";

import { useEffect, useState, useCallback } from "react";
import { api } from "@/lib/api";
import { formatVNDWithComma, formatDate } from "@/utils";

interface OrderItem {
  product_id: { _id: string; name: string; image_url?: string };
  quantity: number;
  price: number;
}

interface Order {
  _id: string;
  user_id?: { full_name: string; email: string; phone?: string };
  items?: OrderItem[];
  total_amount: number;
  status: string;
  payment_method?: string;
  payment_status?: string;
  shipping_address?: string;
  note?: string;
  created_at: string;
}

const STATUS_TABS = [
  { key: "", label: "Tất cả" },
  { key: "pending", label: "Chờ xử lý" },
  { key: "confirmed", label: "Đã xác nhận" },
  { key: "shipping", label: "Đang giao" },
  { key: "delivered", label: "Hoàn thành" },
  { key: "cancelled", label: "Đã hủy" },
];

const STATUS_COLORS: Record<string, string> = {
  pending: "bg-yellow-100 text-yellow-700",
  confirmed: "bg-blue-100 text-blue-700",
  shipping: "bg-indigo-100 text-indigo-700",
  delivered: "bg-green-100 text-green-700",
  cancelled: "bg-red-100 text-red-700",
};

export default function AdminOrdersPage() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeStatus, setActiveStatus] = useState("");
  const [detailOrder, setDetailOrder] = useState<Order | null>(null);

  const fetchOrders = useCallback(async () => {
    setLoading(true);
    try {
      const data = await api.get<{ orders: Order[] }>("/orders/admin/all");
      setOrders(data.orders || []);
    } catch {
      /* ignore */
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchOrders();
  }, [fetchOrders]);

  const filteredOrders = activeStatus
    ? orders.filter((o) => o.status === activeStatus)
    : orders;

  const statusCounts: Record<string, number> = {};
  orders.forEach((o) => {
    statusCounts[o.status] = (statusCounts[o.status] || 0) + 1;
  });

  async function updateStatus(orderId: string, newStatus: string) {
    try {
      await api.put(`/orders/${orderId}/status`, { status: newStatus });
      fetchOrders();
    } catch (err: unknown) {
      alert(err instanceof Error ? err.message : "Lỗi cập nhật trạng thái");
    }
  }

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-gray-800">Quản lý đơn hàng</h1>

      {/* Status Tabs */}
      <div className="flex flex-wrap gap-2">
        {STATUS_TABS.map((tab) => (
          <button
            key={tab.key}
            onClick={() => setActiveStatus(tab.key)}
            className={`px-4 py-2 rounded-lg text-sm font-medium transition ${
              activeStatus === tab.key
                ? "bg-primary text-gray-800"
                : "bg-white border hover:bg-gray-50"
            }`}
          >
            {tab.label}
            {tab.key ? (
              <span className="ml-1">({statusCounts[tab.key] || 0})</span>
            ) : (
              <span className="ml-1">({orders.length})</span>
            )}
          </button>
        ))}
      </div>

      {/* Orders Table */}
      <div className="bg-white rounded-lg shadow overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr className="text-sm text-gray-500">
                <th className="text-left py-3 px-4">Mã đơn</th>
                <th className="text-left py-3 px-4">Khách hàng</th>
                <th className="text-right py-3 px-4">Tổng tiền</th>
                <th className="text-center py-3 px-4">Trạng thái</th>
                <th className="text-center py-3 px-4">Ngày tạo</th>
                <th className="text-center py-3 px-4">Thao tác</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {loading ? (
                <tr>
                  <td colSpan={6} className="py-12 text-center text-gray-400">Đang tải...</td>
                </tr>
              ) : filteredOrders.length === 0 ? (
                <tr>
                  <td colSpan={6} className="py-12 text-center text-gray-400">Không có đơn hàng</td>
                </tr>
              ) : (
                filteredOrders.map((order) => (
                  <tr key={order._id} className="hover:bg-gray-50">
                    <td className="py-3 px-4 text-sm font-mono">{order._id.slice(-8)}</td>
                    <td className="py-3 px-4">
                      <p className="text-sm font-medium text-gray-800">{order.user_id?.full_name || "N/A"}</p>
                      <p className="text-xs text-gray-400">{order.user_id?.email}</p>
                    </td>
                    <td className="py-3 px-4 text-right text-sm font-medium">{formatVNDWithComma(order.total_amount)}đ</td>
                    <td className="py-3 px-4 text-center">
                      <select
                        value={order.status}
                        onChange={(e) => updateStatus(order._id, e.target.value)}
                        className={`px-2 py-1 rounded text-xs font-medium cursor-pointer ${STATUS_COLORS[order.status] || "bg-gray-100"}`}
                      >
                        <option value="pending">Chờ xử lý</option>
                        <option value="confirmed">Đã xác nhận</option>
                        <option value="shipping">Đang giao</option>
                        <option value="delivered">Hoàn thành</option>
                        <option value="cancelled">Đã hủy</option>
                      </select>
                    </td>
                    <td className="py-3 px-4 text-center text-sm text-gray-500">{formatDate(order.created_at)}</td>
                    <td className="py-3 px-4 text-center">
                      <button onClick={() => setDetailOrder(order)} className="px-3 py-1 text-sm border rounded hover:bg-gray-100 transition">
                        Chi tiết
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Detail Modal */}
      {detailOrder && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onClick={() => setDetailOrder(null)}>
          <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-[80vh] overflow-y-auto p-6" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-bold text-gray-800">
                Đơn hàng #{detailOrder._id.slice(-8)}
              </h2>
              <button onClick={() => setDetailOrder(null)} className="text-gray-400 hover:text-gray-600">
                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="text-gray-500">Khách hàng:</span>
                  <p className="font-medium">{detailOrder.user_id?.full_name}</p>
                </div>
                <div>
                  <span className="text-gray-500">Email:</span>
                  <p className="font-medium">{detailOrder.user_id?.email}</p>
                </div>
                <div>
                  <span className="text-gray-500">Tổng tiền:</span>
                  <p className="font-medium text-red-500">{formatVNDWithComma(detailOrder.total_amount)}đ</p>
                </div>
                <div>
                  <span className="text-gray-500">Thanh toán:</span>
                  <p className="font-medium">{detailOrder.payment_method || "COD"}</p>
                </div>
                {detailOrder.shipping_address && (
                  <div className="col-span-2">
                    <span className="text-gray-500">Địa chỉ giao hàng:</span>
                    <p className="font-medium">{detailOrder.shipping_address}</p>
                  </div>
                )}
                {detailOrder.note && (
                  <div className="col-span-2">
                    <span className="text-gray-500">Ghi chú:</span>
                    <p className="font-medium">{detailOrder.note}</p>
                  </div>
                )}
              </div>

              <div className="border-t pt-4">
                <h3 className="font-medium text-gray-800 mb-3">Sản phẩm</h3>
                <div className="space-y-3">
                  {(detailOrder.items || []).map((item, i) => (
                    <div key={i} className="flex items-center gap-3">
                      <img src={item.product_id?.image_url || "/placeholder.png"} alt="" className="w-12 h-12 rounded object-cover border" />
                      <div className="flex-1">
                        <p className="text-sm font-medium">{item.product_id?.name}</p>
                        <p className="text-xs text-gray-400">x{item.quantity}</p>
                      </div>
                      <p className="text-sm font-medium">{formatVNDWithComma(item.price * item.quantity)}đ</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// frontend-nuxt/pages/admin/orders.vue
<template>
  <div>
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-bold text-gray-800">Quản lý đơn hàng</h1>
    </div>

    <!-- Filter tabs -->
    <div class="bg-white rounded-lg shadow mb-6">
      <div class="border-b">
        <div class="flex overflow-x-auto">
          <button
            v-for="tab in statusTabs"
            :key="tab.value"
            class="px-6 py-4 text-sm font-medium whitespace-nowrap border-b-2 transition"
            :class="activeStatus === tab.value 
              ? 'border-yellow-500 text-yellow-600' 
              : 'border-transparent text-gray-500 hover:text-gray-700'"
            @click="filterByStatus(tab.value)"
          >
            {{ tab.label }}
            <span 
              v-if="getOrderCountByStatus(tab.value) > 0"
              class="ml-1.5 px-2 py-0.5 text-xs rounded-full"
              :class="activeStatus === tab.value ? 'bg-yellow-100 text-yellow-700' : 'bg-gray-100 text-gray-600'"
            >
              {{ getOrderCountByStatus(tab.value) }}
            </span>
          </button>
        </div>
      </div>
    </div>

    <!-- Orders Table -->
    <div class="bg-white rounded-lg shadow overflow-hidden">
      <!-- Loading -->
      <div v-if="loading" class="flex items-center justify-center py-12">
        <svg class="animate-spin h-8 w-8 text-yellow-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
      </div>

      <table v-else class="w-full">
        <thead class="bg-gray-50 border-b">
          <tr>
            <th class="text-left px-6 py-4 text-sm font-semibold text-gray-600">Mã đơn</th>
            <th class="text-left px-6 py-4 text-sm font-semibold text-gray-600">Khách hàng</th>
            <th class="text-right px-6 py-4 text-sm font-semibold text-gray-600">Tổng tiền</th>
            <th class="text-center px-6 py-4 text-sm font-semibold text-gray-600">Trạng thái</th>
            <th class="text-center px-6 py-4 text-sm font-semibold text-gray-600">Ngày đặt</th>
            <th class="text-center px-6 py-4 text-sm font-semibold text-gray-600">Thao tác</th>
          </tr>
        </thead>
        <tbody class="divide-y">
          <tr v-for="order in orders" :key="order.id" class="hover:bg-gray-50">
            <td class="px-6 py-4">
              <p class="font-medium text-gray-800">TMF{{ String(order.id).padStart(8, '0') }}</p>
              <p class="text-sm text-gray-500">{{ order.items?.length || 0 }} sản phẩm</p>
            </td>
            <td class="px-6 py-4">
              <p class="font-medium text-gray-800">{{ order.user?.fullName || 'Khách' }}</p>
              <p class="text-sm text-gray-500">{{ order.user?.email }}</p>
              <p v-if="order.phone" class="text-sm text-gray-500">{{ order.phone }}</p>
            </td>
            <td class="px-6 py-4 text-right">
              <p class="font-bold text-red-500">{{ formatVNDWithComma(order.totalAmount) }}đ</p>
            </td>
            <td class="px-6 py-4 text-center">
              <select
                :value="order.status"
                class="px-3 py-1 text-sm border rounded-lg focus:outline-none focus:ring-2 focus:ring-yellow-400"
                :class="getStatusSelectClass(order.status)"
                @change="updateStatus(order, ($event.target as HTMLSelectElement).value)"
              >
                <option value="PENDING">Chờ xác nhận</option>
                <option value="CONFIRMED">Đã xác nhận</option>
                <option value="SHIPPING">Đang giao</option>
                <option value="COMPLETED">Hoàn thành</option>
                <option value="CANCELLED">Đã hủy</option>
              </select>
            </td>
            <td class="px-6 py-4 text-center text-gray-600">
              {{ formatDate(order.createdAt) }}
            </td>
            <td class="px-6 py-4">
              <div class="flex items-center justify-center">
                <button
                  class="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition"
                  title="Xem chi tiết"
                  @click="viewOrder(order)"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                  </svg>
                </button>
              </div>
            </td>
          </tr>
          <tr v-if="orders.length === 0">
            <td colspan="6" class="px-6 py-12 text-center text-gray-500">
              Không có đơn hàng nào
            </td>
          </tr>
        </tbody>
      </table>

      <!-- Pagination -->
      <div v-if="pagination.totalPages > 1" class="px-6 py-4 border-t flex items-center justify-between">
        <p class="text-sm text-gray-600">
          Hiển thị {{ (pagination.page - 1) * pagination.limit + 1 }} - 
          {{ Math.min(pagination.page * pagination.limit, pagination.total) }} 
          trong {{ pagination.total }} đơn hàng
        </p>
        <div class="flex gap-2">
          <button
            :disabled="pagination.page <= 1"
            class="px-3 py-1 border rounded hover:bg-gray-100 disabled:opacity-50"
            @click="goToPage(pagination.page - 1)"
          >
            Trước
          </button>
          <button
            :disabled="pagination.page >= pagination.totalPages"
            class="px-3 py-1 border rounded hover:bg-gray-100 disabled:opacity-50"
            @click="goToPage(pagination.page + 1)"
          >
            Sau
          </button>
        </div>
      </div>
    </div>

    <!-- Order Detail Modal -->
    <div
      v-if="selectedOrder"
      class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
      @click.self="selectedOrder = null"
    >
      <div class="bg-white rounded-lg shadow-xl max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto">
        <div class="p-6 border-b sticky top-0 bg-white">
          <div class="flex items-center justify-between">
            <h2 class="text-xl font-bold text-gray-800">
              Chi tiết đơn hàng #TMF{{ String(selectedOrder.id).padStart(8, '0') }}
            </h2>
            <button
              class="p-2 hover:bg-gray-100 rounded-lg transition"
              @click="selectedOrder = null"
            >
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        <div class="p-6">
          <!-- Customer Info -->
          <div class="mb-6">
            <h3 class="font-semibold text-gray-800 mb-3">Thông tin khách hàng</h3>
            <div class="bg-gray-50 rounded-lg p-4 space-y-2">
              <p><span class="text-gray-500">Họ tên:</span> {{ selectedOrder.user?.fullName || 'N/A' }}</p>
              <p><span class="text-gray-500">Email:</span> {{ selectedOrder.user?.email }}</p>
              <p><span class="text-gray-500">SĐT:</span> {{ selectedOrder.phone || 'N/A' }}</p>
              <p><span class="text-gray-500">Địa chỉ:</span> {{ selectedOrder.shippingAddress || 'N/A' }}</p>
              <p v-if="selectedOrder.note"><span class="text-gray-500">Ghi chú:</span> {{ selectedOrder.note }}</p>
            </div>
          </div>

          <!-- Order Items -->
          <div class="mb-6">
            <h3 class="font-semibold text-gray-800 mb-3">Sản phẩm</h3>
            <div class="space-y-3">
              <div
                v-for="item in selectedOrder.items"
                :key="item.id"
                class="flex items-center gap-4 p-3 border rounded-lg"
              >
                <img
                  :src="item.product?.imageUrl || '/placeholder.png'"
                  :alt="item.product?.name"
                  class="w-16 h-16 object-cover rounded-lg"
                />
                <div class="flex-1">
                  <p class="font-medium text-gray-800">{{ item.product?.name }}</p>
                  <p class="text-sm text-gray-500">
                    {{ formatVNDWithComma(item.price) }}đ x {{ item.quantity }}
                  </p>
                </div>
                <p class="font-bold text-gray-800">
                  {{ formatVNDWithComma(item.price * item.quantity) }}đ
                </p>
              </div>
            </div>
          </div>

          <!-- Order Summary -->
          <div class="border-t pt-4">
            <div class="flex justify-between items-center">
              <span class="text-gray-600">Tổng tiền:</span>
              <span class="text-xl font-bold text-red-500">
                {{ formatVNDWithComma(selectedOrder.totalAmount) }}đ
              </span>
            </div>
            <div class="flex justify-between items-center mt-2">
              <span class="text-gray-600">Trạng thái:</span>
              <span 
                class="px-3 py-1 rounded-full text-sm font-medium"
                :class="getStatusClass(selectedOrder.status)"
              >
                {{ getStatusLabel(selectedOrder.status) }}
              </span>
            </div>
            <div class="flex justify-between items-center mt-2">
              <span class="text-gray-600">Ngày đặt:</span>
              <span class="text-gray-800">{{ formatDate(selectedOrder.createdAt) }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useAuthStore } from '~/store/auth'
import clientAPI from '~/services/_AxiosConfig'

definePageMeta({
  layout: 'admin',
  middleware: 'admin',
})

const authStore = useAuthStore()
const route = useRoute()

interface OrderItem {
  id: number
  quantity: number
  price: number
  product: {
    id: number
    name: string
    imageUrl: string | null
  } | null
}

interface Order {
  id: number
  status: string
  totalAmount: number
  shippingAddress: string | null
  phone: string | null
  note: string | null
  createdAt: string
  user: {
    id: number
    email: string
    fullName: string | null
  } | null
  items: OrderItem[]
}

const loading = ref(true)
const orders = ref<Order[]>([])
const allOrders = ref<Order[]>([])
const selectedOrder = ref<Order | null>(null)
const activeStatus = ref('ALL')

const pagination = ref({
  page: 1,
  limit: 20,
  total: 0,
  totalPages: 0,
})

const statusTabs = [
  { label: 'Tất cả', value: 'ALL' },
  { label: 'Chờ xác nhận', value: 'PENDING' },
  { label: 'Đã xác nhận', value: 'CONFIRMED' },
  { label: 'Đang giao', value: 'SHIPPING' },
  { label: 'Hoàn thành', value: 'COMPLETED' },
  { label: 'Đã hủy', value: 'CANCELLED' },
]

function getOrderCountByStatus(status: string) {
  if (status === 'ALL') return allOrders.value.length
  return allOrders.value.filter(o => o.status === status).length
}

function getStatusLabel(status: string) {
  const labels: Record<string, string> = {
    PENDING: 'Chờ xác nhận',
    CONFIRMED: 'Đã xác nhận',
    SHIPPING: 'Đang giao',
    COMPLETED: 'Hoàn thành',
    CANCELLED: 'Đã hủy',
  }
  return labels[status] || status
}

function getStatusClass(status: string) {
  const classes: Record<string, string> = {
    PENDING: 'bg-yellow-100 text-yellow-800',
    CONFIRMED: 'bg-blue-100 text-blue-800',
    SHIPPING: 'bg-purple-100 text-purple-800',
    COMPLETED: 'bg-green-100 text-green-800',
    CANCELLED: 'bg-red-100 text-red-800',
  }
  return classes[status] || 'bg-gray-100 text-gray-800'
}

function getStatusSelectClass(status: string) {
  const classes: Record<string, string> = {
    PENDING: 'bg-yellow-50 text-yellow-800 border-yellow-200',
    CONFIRMED: 'bg-blue-50 text-blue-800 border-blue-200',
    SHIPPING: 'bg-purple-50 text-purple-800 border-purple-200',
    COMPLETED: 'bg-green-50 text-green-800 border-green-200',
    CANCELLED: 'bg-red-50 text-red-800 border-red-200',
  }
  return classes[status] || ''
}

function formatDate(dateString: string) {
  const date = new Date(dateString)
  return date.toLocaleDateString('vi-VN', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

async function fetchOrders() {
  loading.value = true
  try {
    const params = new URLSearchParams()
    params.append('page', String(pagination.value.page))
    params.append('limit', String(pagination.value.limit))
    if (activeStatus.value !== 'ALL') {
      params.append('status', activeStatus.value)
    }

    const response = await clientAPI().get(`/admin/orders?${params.toString()}`, {
      headers: authStore.getAuthHeaders(),
    })
    
    orders.value = response.data.orders || []
    
    if (response.data.pagination) {
      pagination.value = response.data.pagination
    }

    // Fetch all for counts (first time only)
    if (allOrders.value.length === 0) {
      const allRes = await clientAPI().get('/admin/orders?limit=1000', {
        headers: authStore.getAuthHeaders(),
      })
      allOrders.value = allRes.data.orders || []
    }
  } catch (err) {
    console.error('Fetch orders error:', err)
  } finally {
    loading.value = false
  }
}

function filterByStatus(status: string) {
  activeStatus.value = status
  pagination.value.page = 1
  fetchOrders()
}

async function updateStatus(order: Order, newStatus: string) {
  try {
    await clientAPI().put(`/admin/orders/${order.id}`, {
      status: newStatus,
    }, {
      headers: authStore.getAuthHeaders(),
    })
    
    order.status = newStatus
    
    // Update in allOrders too
    const idx = allOrders.value.findIndex(o => o.id === order.id)
    if (idx !== -1) {
      allOrders.value[idx].status = newStatus
    }
  } catch (err: any) {
    alert(err.response?.data?.error || 'Lỗi cập nhật trạng thái')
  }
}

function viewOrder(order: Order) {
  selectedOrder.value = order
}

function goToPage(page: number) {
  pagination.value.page = page
  fetchOrders()
}

onMounted(() => {
  // Check URL param for status filter
  const statusParam = route.query.status as string
  if (statusParam) {
    activeStatus.value = statusParam
  }
  fetchOrders()
})
</script>
