// apps/frontend-next/src/app/admin/report/page.tsx
// ===== TMFashion Admin Report Page =====
// Tương đương pages/admin/report.vue (~695 lines)
// SD: Quản lý doanh thu → Admin xem báo cáo doanh thu
// STM Quản lý doanh thu: Xem tổng quan → Chọn khoảng thời gian → So sánh → Xuất CSV

"use client";

import { useEffect, useState, useCallback } from "react";
import { api } from "@/lib/api";
import { formatVNDWithComma } from "@/utils";

interface MonthlyData {
  _id: { year: number; month: number };
  revenue: number;
  orderCount: number;
}

interface TopProduct {
  productId: string;
  productName: string;
  productImage?: string;
  totalSold: number;
  totalRevenue: number;
}

interface OrderStatsData {
  orderStats: Record<string, { count: number; totalAmount: number }>;
}

interface OverviewData {
  totalRevenue: number;
  totalOrders: number;
  totalUsers: number;
  totalProducts: number;
}

const MONTHS = ["T1", "T2", "T3", "T4", "T5", "T6", "T7", "T8", "T9", "T10", "T11", "T12"];

export default function AdminReportPage() {
  const [overview, setOverview] = useState<OverviewData | null>(null);
  const [chartData, setChartData] = useState<MonthlyData[]>([]);
  const [lastYearData, setLastYearData] = useState<MonthlyData[]>([]);
  const [topProducts, setTopProducts] = useState<TopProduct[]>([]);
  const [orderStats, setOrderStats] = useState<OrderStatsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1);
  const [compareResult, setCompareResult] = useState<{ current: number; previous: number; change: number } | null>(null);
  const [exporting, setExporting] = useState(false);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const currentYear = new Date().getFullYear();
      const [ov, chart, lastYear, top, stats] = await Promise.all([
        api.get<OverviewData>("/admin/revenue/overview"),
        api.get<{ data: MonthlyData[] }>("/admin/revenue/chart", { year: currentYear }),
        api.get<{ data: MonthlyData[] }>("/admin/revenue/chart", { year: currentYear - 1 }),
        api.get<{ topProducts: TopProduct[] }>("/admin/revenue/top-products", { limit: 10 }),
        api.get<OrderStatsData>("/admin/revenue/order-stats"),
      ]);
      setOverview(ov);
      setChartData(chart.data || []);
      setLastYearData(lastYear.data || []);
      setTopProducts(top.topProducts || []);
      setOrderStats(stats);
    } catch {
      /* ignore */
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  // Compare months
  async function handleCompare() {
    try {
      const currentYear = new Date().getFullYear();
      const data = await api.get<{ currentMonth: { revenue: number }; previousMonth: { revenue: number }; comparison: { revenueChange: number } }>(
        "/admin/revenue/compare",
        { month: selectedMonth, year: currentYear }
      );
      setCompareResult({
        current: data.currentMonth?.revenue || 0,
        previous: data.previousMonth?.revenue || 0,
        change: data.comparison?.revenueChange || 0,
      });
    } catch {
      setCompareResult(null);
    }
  }

  // Export CSV
  async function handleExportCSV() {
    setExporting(true);
    try {
      const res = await fetch(`http://localhost:8000/admin/revenue/export`, {
        headers: { Authorization: `Bearer ${localStorage.getItem("tmf_token") || ""}` },
      });
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `revenue-report-${new Date().toISOString().slice(0, 10)}.csv`;
      a.click();
      window.URL.revokeObjectURL(url);
    } catch {
      alert("Lỗi xuất CSV");
    } finally {
      setExporting(false);
    }
  }

  // SVG Line Chart helper
  const chartWidth = 700;
  const chartHeight = 300;
  const padding = 40;

  function getMaxRevenue() {
    const allValues = [...chartData.map((d) => d.revenue), ...lastYearData.map((d) => d.revenue)];
    return Math.max(...allValues, 1);
  }

  function toPoint(month: number, revenue: number, maxRev: number) {
    const x = padding + ((month - 1) / 11) * (chartWidth - 2 * padding);
    const y = chartHeight - padding - (revenue / maxRev) * (chartHeight - 2 * padding);
    return { x, y };
  }

  function buildPath(data: MonthlyData[], maxRev: number) {
    const points = Array.from({ length: 12 }, (_, i) => {
      const d = data.find((d) => (d._id?.month || 0) === i + 1);
      return toPoint(i + 1, d?.revenue || 0, maxRev);
    });
    return points.map((p, i) => `${i === 0 ? "M" : "L"}${p.x},${p.y}`).join(" ");
  }

  if (loading) {
    return <div className="text-center py-12 text-gray-400">Đang tải báo cáo...</div>;
  }

  const maxRev = getMaxRevenue();

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-800">Báo cáo doanh thu</h1>
        <button
          onClick={handleExportCSV}
          disabled={exporting}
          className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-medium rounded-lg transition disabled:opacity-50"
        >
          {exporting ? "Đang xuất..." : "Xuất CSV"}
        </button>
      </div>

      {/* Overview Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white rounded-lg shadow p-6">
          <p className="text-sm text-gray-500">Tổng doanh thu</p>
          <p className="text-2xl font-bold text-red-500">{formatVNDWithComma(overview?.totalRevenue || 0)}đ</p>
        </div>
        <div className="bg-white rounded-lg shadow p-6">
          <p className="text-sm text-gray-500">Tổng đơn hàng</p>
          <p className="text-2xl font-bold text-blue-600">{overview?.totalOrders || 0}</p>
        </div>
        <div className="bg-white rounded-lg shadow p-6">
          <p className="text-sm text-gray-500">Giá trị TB / đơn</p>
          <p className="text-2xl font-bold text-orange-500">{formatVNDWithComma(overview?.totalRevenue && overview?.totalOrders ? Math.round(overview.totalRevenue / overview.totalOrders) : 0)}đ</p>
        </div>
      </div>

      {/* Revenue Chart (SVG) */}
      <div className="bg-white rounded-lg shadow p-6">
        <h2 className="text-lg font-semibold text-gray-800 mb-4">Biểu đồ doanh thu theo tháng</h2>
        <div className="overflow-x-auto">
          <svg viewBox={`0 0 ${chartWidth} ${chartHeight}`} className="w-full min-w-[500px]">
            {/* Grid lines */}
            {[0, 0.25, 0.5, 0.75, 1].map((ratio) => {
              const y = chartHeight - padding - ratio * (chartHeight - 2 * padding);
              return (
                <g key={ratio}>
                  <line x1={padding} y1={y} x2={chartWidth - padding} y2={y} stroke="#e5e7eb" strokeDasharray="4" />
                  <text x={padding - 5} y={y + 4} textAnchor="end" fill="#9ca3af" fontSize="10">
                    {formatVNDWithComma(Math.round(maxRev * ratio))}
                  </text>
                </g>
              );
            })}

            {/* X axis labels */}
            {MONTHS.map((m, i) => {
              const pt = toPoint(i + 1, 0, maxRev);
              return (
                <text key={m} x={pt.x} y={chartHeight - 10} textAnchor="middle" fill="#6b7280" fontSize="11">
                  {m}
                </text>
              );
            })}

            {/* Last year line */}
            <path d={buildPath(lastYearData, maxRev)} fill="none" stroke="#d1d5db" strokeWidth="2" strokeDasharray="6" />

            {/* This year line */}
            <path d={buildPath(chartData, maxRev)} fill="none" stroke="#FED519" strokeWidth="3" />

            {/* This year dots */}
            {Array.from({ length: 12 }, (_, i) => {
              const d = chartData.find((d) => (d._id?.month || 0) === i + 1);
              const pt = toPoint(i + 1, d?.revenue || 0, maxRev);
              return (
                <circle key={i} cx={pt.x} cy={pt.y} r="4" fill="#FED519" stroke="white" strokeWidth="2" />
              );
            })}

            {/* Legend */}
            <rect x={chartWidth - 200} y={10} width={12} height={3} fill="#FED519" />
            <text x={chartWidth - 183} y={14} fill="#374151" fontSize="11">Năm nay</text>
            <line x1={chartWidth - 200} y1={28} x2={chartWidth - 188} y2={28} stroke="#d1d5db" strokeWidth="2" strokeDasharray="4" />
            <text x={chartWidth - 183} y={32} fill="#6b7280" fontSize="11">Năm trước</text>
          </svg>
        </div>
      </div>

      {/* Month Comparison */}
      <div className="bg-white rounded-lg shadow p-6">
        <h2 className="text-lg font-semibold text-gray-800 mb-4">So sánh doanh thu tháng</h2>
        <div className="flex flex-wrap items-end gap-4">
          <div>
            <label className="block text-sm text-gray-500 mb-1">Tháng</label>
            <select value={selectedMonth} onChange={(e) => setSelectedMonth(Number(e.target.value))} className="px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary">
              {MONTHS.map((m, i) => <option key={i} value={i + 1}>{m}</option>)}
            </select>
          </div>
          <button onClick={handleCompare} className="px-4 py-2 bg-primary hover:bg-yellow-400 text-gray-800 font-medium rounded-lg transition">
            So sánh với tháng trước
          </button>
        </div>
        {compareResult && (
          <div className="mt-4 grid grid-cols-3 gap-4 p-4 bg-gray-50 rounded-lg">
            <div>
              <p className="text-sm text-gray-500">Tháng hiện tại</p>
              <p className="text-lg font-bold">{formatVNDWithComma(compareResult.current)}đ</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Tháng trước</p>
              <p className="text-lg font-bold">{formatVNDWithComma(compareResult.previous)}đ</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Thay đổi</p>
              <p className={`text-lg font-bold ${compareResult.change >= 0 ? "text-green-600" : "text-red-600"}`}>
                {compareResult.change >= 0 ? "+" : ""}{compareResult.change.toFixed(1)}%
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Top Products & Order Stats */}
      <div className="grid lg:grid-cols-2 gap-6">
        {/* Top Products */}
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-gray-800 mb-4">Top sản phẩm bán chạy</h2>
          <div className="space-y-3">
            {topProducts.length === 0 ? (
              <p className="text-gray-400 text-sm">Chưa có dữ liệu</p>
            ) : (
              topProducts.map((item, i) => {
                const maxQty = topProducts[0]?.totalSold || 1;
                const barWidth = (item.totalSold / maxQty) * 100;
                return (
                  <div key={item.productId}>
                    <div className="flex items-center justify-between text-sm mb-1">
                      <span className="flex items-center gap-2">
                        <span className="text-gray-400 font-mono w-5">#{i + 1}</span>
                        <span className="font-medium text-gray-800 line-clamp-1">{item.productName}</span>
                      </span>
                      <span className="text-gray-500 whitespace-nowrap ml-2">{item.totalSold} đã bán</span>
                    </div>
                    <div className="w-full bg-gray-100 rounded-full h-2">
                      <div className="bg-primary rounded-full h-2 transition-all" style={{ width: `${barWidth}%` }} />
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* Order Stats */}
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-gray-800 mb-4">Thống kê đơn hàng</h2>
          {orderStats?.orderStats ? (
            <div className="space-y-4">
              <div className="text-center">
                <p className="text-3xl font-bold text-gray-800">{Object.values(orderStats.orderStats).reduce((sum, s) => sum + s.count, 0)}</p>
                <p className="text-sm text-gray-500">Tổng số đơn hàng</p>
              </div>
              <div className="space-y-2">
                {Object.entries(orderStats.orderStats).map(([status, stat]) => {
                  const total = Object.values(orderStats.orderStats).reduce((sum, s) => sum + s.count, 0) || 1;
                  const pct = (stat.count / total) * 100;
                  const colors: Record<string, string> = {
                    pending: "bg-yellow-400",
                    confirmed: "bg-blue-400",
                    shipping: "bg-indigo-400",
                    delivered: "bg-green-400",
                    cancelled: "bg-red-400",
                  };
                  return (
                    <div key={status}>
                      <div className="flex justify-between text-sm mb-1">
                        <span className="capitalize text-gray-600">{status}</span>
                        <span className="text-gray-500">{stat.count} ({pct.toFixed(0)}%)</span>
                      </div>
                      <div className="w-full bg-gray-100 rounded-full h-2">
                        <div className={`${colors[status] || "bg-gray-400"} rounded-full h-2`} style={{ width: `${pct}%` }} />
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          ) : (
            <p className="text-gray-400 text-sm">Chưa có dữ liệu</p>
          )}
        </div>
      </div>
    </div>
  );
}

// frontend-nuxt/pages/admin/report.vue
<template>
  <div class="p-6">
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-bold text-gray-800">Báo cáo - Doanh thu</h1>

      <div class="flex items-center gap-3">
        <select v-model="months" class="px-3 py-2 border rounded text-sm">
          <option :value="1">1 tháng</option>
          <option :value="3">3 tháng</option>
          <option :value="6">6 tháng</option>
          <option :value="12">12 tháng</option>
        </select>

        <button
          @click="refresh"
          class="px-3 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 text-sm"
        >
          Làm mới
        </button>

        <button
          @click="exportCSV"
          class="px-3 py-2 bg-green-600 text-white rounded hover:bg-green-700 text-sm"
        >
          Xuất CSV
        </button>
      </div>
    </div>

    <div v-if="loading" class="flex items-center justify-center py-12">
      <svg
        class="animate-spin h-8 w-8 text-yellow-500"
        viewBox="0 0 24 24"
        fill="none"
      >
        <circle
          class="opacity-25"
          cx="12"
          cy="12"
          r="10"
          stroke="currentColor"
          stroke-width="4"
        ></circle>
        <path
          class="opacity-75"
          fill="currentColor"
          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
        ></path>
      </svg>
    </div>

    <div v-else class="space-y-6 relative">
      <!-- Summary row -->
      <div class="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <div class="bg-white p-4 rounded shadow">
          <div class="text-sm text-gray-500">Tổng doanh thu</div>
          <div class="text-2xl font-bold mt-2">
            {{ formatCurrency(summary.totalRevenue) }}
          </div>
          <div class="text-xs text-gray-400 mt-1">
            Khoảng thời gian: {{ months }} tháng
          </div>
        </div>

        <!-- DOANH THU THEO THÁNG with month picker & comparison -->
        <div class="bg-white p-4 rounded shadow">
          <div class="flex items-center justify-between">
            <div>
              <div class="text-sm text-gray-500">Doanh thu theo tháng</div>
              <div class="text-2xl font-bold mt-2">
                {{ formatCurrency(selectedMonthRevenue) }}
              </div>
              <div class="text-xs text-gray-400 mt-1">
                Tháng đã chọn: {{ selectedMonthLabel || "—" }}
              </div>
            </div>

            <div class="flex flex-col items-end">
              <label class="text-xs text-gray-500 mb-1">Chọn tháng</label>
              <select
                v-model.number="selectedMonthIndex"
                class="px-3 py-2 border rounded text-sm bg-white"
              >
                <option v-for="(lab, idx) in labels" :key="lab" :value="idx">
                  {{ lab }}
                </option>
              </select>

              <div v-if="selectedMonthIndex !== null" class="mt-2 text-right">
                <div
                  class="text-sm"
                  :class="changeIsPositive ? 'text-green-600' : 'text-red-600'"
                >
                  {{ changeSign }} {{ formatCurrency(changeValue) }}
                  <span class="text-xs text-gray-500 ml-2"
                    >({{ changePercentLabel }})</span
                  >
                </div>
                <div class="text-xs text-gray-400 mt-1">
                  So sánh với tháng trước
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="bg-white p-4 rounded shadow">
          <div class="text-sm text-gray-500">Tổng đơn hàng</div>
          <div class="text-2xl font-bold mt-2">
            {{ summary.totalOrders.toLocaleString() }}
          </div>
          <div class="text-xs text-gray-400 mt-1">Số đơn đã xử lý</div>
        </div>

        <div class="bg-white p-4 rounded shadow">
          <div class="text-sm text-gray-500">Giá trị đơn trung bình (AOV)</div>
          <div class="text-2xl font-bold mt-2">
            {{ formatCurrency(summary.avgOrderValue) }}
          </div>
          <div class="text-xs text-gray-400 mt-1">Average Order Value</div>
        </div>
      </div>

      <!-- Charts area -->
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <!-- Line chart -->
        <div class="bg-white p-4 rounded shadow relative">
          <div class="flex items-center justify-between mb-3">
            <div>
              <h3 class="text-lg font-medium">Doanh thu theo tháng</h3>
              <p class="text-xs text-gray-500">So sánh Năm nay vs Năm trước</p>
            </div>
          </div>

          <div ref="lineWrapper" class="w-full h-64 relative">
            <svg :viewBox="`0 0 ${LINE_W} ${LINE_H}`" class="w-full h-full">
              <g v-for="i in 5" :key="'grid-' + i">
                <line
                  :x1="padding"
                  :x2="LINE_W - padding"
                  :y1="padTop + (i - 1) * gridStep"
                  :y2="padTop + (i - 1) * gridStep"
                  stroke="#e6e7eb"
                />
              </g>

              <!-- area this year -->
              <path
                v-if="thisYearPoints.length"
                :d="areaPath(thisYearPoints)"
                fill="rgba(37,99,235,0.06)"
                stroke="none"
              />

              <!-- line this year -->
              <path
                v-if="thisYearPoints.length"
                :d="linePath(thisYearPoints)"
                fill="none"
                stroke="#2563eb"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              />

              <!-- area last year -->
              <path
                v-if="lastYearPoints.length"
                :d="areaPath(lastYearPoints)"
                fill="rgba(16,185,129,0.04)"
                stroke="none"
              />

              <!-- line last year -->
              <path
                v-if="lastYearPoints.length"
                :d="linePath(lastYearPoints)"
                fill="none"
                stroke="#10b981"
                stroke-width="2"
                stroke-dasharray="6 4"
              />

              <!-- points this year (interactive) -->
              <g v-for="(p, idx) in thisYearPoints" :key="'pt-' + idx">
                <circle
                  :cx="p.x"
                  :cy="p.y"
                  r="4"
                  fill="#2563eb"
                  @mouseenter="showPointTooltip(p, idx, 'this')"
                  @mouseleave="hideTooltip"
                />
              </g>

              <!-- points last year (small) -->
              <g v-for="(p, idx) in lastYearPoints" :key="'ptL-' + idx">
                <circle
                  :cx="p.x"
                  :cy="p.y"
                  r="3"
                  fill="#10b981"
                  @mouseenter="showPointTooltip(p, idx, 'last')"
                  @mouseleave="hideTooltip"
                />
              </g>

              <!-- x labels -->
              <g v-for="(lab, idx) in labels" :key="'xl-' + idx">
                <text
                  :x="xForIndex(idx)"
                  :y="LINE_H - 6"
                  font-size="10"
                  fill="#6b7280"
                  text-anchor="middle"
                >
                  {{ lab }}
                </text>
              </g>
            </svg>

            <!-- Tooltip absolute -->
            <div
              v-if="tooltip.visible"
              :style="tooltipStyle"
              class="pointer-events-none z-50"
            >
              <div class="bg-white border rounded shadow px-3 py-2 text-sm">
                <div class="text-xs text-gray-500">{{ tooltip.label }}</div>
                <div class="font-medium">
                  {{ formatCurrency(tooltip.value) }}
                </div>
                <div class="text-xs text-gray-400">{{ tooltip.note }}</div>
              </div>
            </div>
          </div>
        </div>

        <!-- Top products (list + images) -->
        <div class="bg-white p-4 rounded shadow">
          <div class="flex items-center justify-between mb-3">
            <div>
              <h3 class="text-lg font-medium">Sản phẩm bán chạy</h3>
              <p class="text-xs text-gray-500">Top theo số lượng</p>
            </div>
          </div>

          <div class="space-y-3">
            <div
              v-for="(p, idx) in topProductsDisplay"
              :key="p.id || idx"
              class="flex items-center gap-3"
            >
              <div class="w-8 text-sm text-gray-600">{{ idx + 1 }}</div>

              <div
                class="w-12 h-12 rounded overflow-hidden bg-slate-100 flex items-center justify-center"
              >
                <img
                  v-if="p.imageUrl"
                  :src="p.imageUrl"
                  alt=""
                  class="object-cover w-full h-full"
                />
                <span v-else class="text-xs text-gray-500">No image</span>
              </div>

              <div class="flex-1">
                <div class="flex justify-between items-center">
                  <div class="truncate font-medium">{{ p.name }}</div>
                  <div class="text-sm text-gray-600">
                    {{ p.sold.toLocaleString() }}
                  </div>
                </div>

                <div
                  class="w-full bg-slate-100 h-2 rounded mt-1 overflow-hidden"
                >
                  <div
                    :style="{
                      width: `${Math.round((p.sold / maxSold) * 100)}%`,
                    }"
                    class="h-2 bg-yellow-400 rounded"
                    @mouseenter="showBarTooltip($event, p)"
                    @mouseleave="hideTooltip"
                  ></div>
                </div>
              </div>
            </div>

            <div
              v-if="topProductsDisplay.length === 0"
              class="text-center text-gray-500 py-6"
            >
              Không có dữ liệu
            </div>
          </div>
        </div>
      </div>

      <!-- Table -->
      <div class="bg-white p-4 rounded shadow">
        <div class="flex items-center justify-between mb-3">
          <h4 class="font-medium">Top sản phẩm (bảng)</h4>
          <div class="text-sm text-gray-500">Top {{ topProducts.length }}</div>
        </div>

        <div class="overflow-x-auto">
          <table class="w-full text-left">
            <thead class="text-sm text-gray-500 border-b">
              <tr>
                <th class="py-2 px-3">#</th>
                <th class="py-2 px-3">Sản phẩm</th>
                <th class="py-2 px-3">Số lượng</th>
                <th class="py-2 px-3">Doanh thu</th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="(p, idx) in topProducts"
                :key="p.id || idx"
                class="border-b hover:bg-slate-50"
              >
                <td class="py-2 px-3">{{ idx + 1 }}</td>
                <td class="py-2 px-3 flex items-center gap-3">
                  <div
                    class="w-10 h-10 rounded overflow-hidden bg-slate-100 flex items-center justify-center"
                  >
                    <img
                      v-if="p.imageUrl"
                      :src="p.imageUrl"
                      alt=""
                      class="object-cover w-full h-full"
                    />
                    <span v-else class="text-xs text-gray-500">No image</span>
                  </div>
                  <div>
                    <div class="font-medium">{{ p.name }}</div>
                    <div class="text-xs text-gray-400">
                      {{ p.id ? "#" + p.id : "" }}
                    </div>
                  </div>
                </td>
                <td class="py-2 px-3">{{ p.sold.toLocaleString() }}</td>
                <td class="py-2 px-3">{{ formatCurrency(p.revenue) }}</td>
              </tr>

              <tr v-if="topProducts.length === 0">
                <td colspan="4" class="py-4 text-center text-gray-500">
                  Không có dữ liệu
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="text-xs text-gray-400">Dữ liệu: {{ dataSourceLabel }}</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from "vue";
import { useRuntimeConfig } from "#app";
import { useAuthStore } from "~/store/auth";
import clientAPI from "~/services/_AxiosConfig";

definePageMeta({
  layout: "admin",
  middleware: "admin",
});

// SVG layout constants
const LINE_W = 900;
const LINE_H = 300;
const padding = 40;
const padTop = 20;
const padBottom = 40;
const gridStep = (LINE_H - padTop - padBottom) / 4;

type TopProduct = {
  id?: number;
  name: string;
  sold: number;
  revenue: number;
  imageUrl?: string | null;
};

const months = ref<number>(12);
const loading = ref(true);
const dataSourceLabel = ref("Dữ liệu từ API");

const summary = ref({ totalRevenue: 0, totalOrders: 0, avgOrderValue: 0 });
const labels = ref<string[]>([]);
const thisYear = ref<number[]>([]);
const lastYear = ref<number[]>([]);
const topProducts = ref<TopProduct[]>([]);

const config = useRuntimeConfig();
const apiBase = config.public?.apiBase || "http://localhost:4005/api";

const authStore = useAuthStore();

// monthly revenue (last entry of thisYear)
const monthlyRevenue = computed(() => {
  if (!thisYear.value.length) return 0;
  return thisYear.value[thisYear.value.length - 1] ?? 0;
});

// ---------- Month picker & comparison ----------
const selectedMonthIndex = ref<number | null>(null);

watch(
  [labels, thisYear],
  () => {
    if (labels.value.length > 0) {
      if (selectedMonthIndex.value === null) {
        selectedMonthIndex.value = labels.value.length - 1;
      } else {
        selectedMonthIndex.value = Math.min(
          selectedMonthIndex.value,
          labels.value.length - 1
        );
      }
    } else {
      selectedMonthIndex.value = null;
    }
  },
  { immediate: true }
);

const selectedMonthLabel = computed(() => {
  if (selectedMonthIndex.value === null) return "";
  return labels.value[selectedMonthIndex.value] ?? "";
});

const selectedMonthRevenue = computed(() => {
  if (selectedMonthIndex.value === null) return 0;
  return Number(thisYear.value[selectedMonthIndex.value] ?? 0);
});

const previousMonthRevenue = computed(() => {
  if (selectedMonthIndex.value === null) return 0;
  const idx = selectedMonthIndex.value - 1;
  if (idx < 0) return 0;
  return Number(thisYear.value[idx] ?? 0);
});

const changeValue = computed(
  () => selectedMonthRevenue.value - previousMonthRevenue.value
);
const changePercent = computed(() => {
  const prev = previousMonthRevenue.value;
  if (prev === 0) return selectedMonthRevenue.value === 0 ? 0 : 100;
  return Math.round((changeValue.value / prev) * 100);
});
const changeIsPositive = computed(() => changeValue.value >= 0);
const changeSign = computed(() => (changeIsPositive.value ? "+" : "−"));
const changePercentLabel = computed(() => `${changePercent.value}%`);

// ---------- formatting ----------
function formatCurrency(v: number) {
  return new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
    maximumFractionDigits: 0,
  }).format(v);
}

// fetch from API using clientAPI + auth headers
async function fetchReport(m = 12) {
  loading.value = true;
  try {
    const headers = authStore.getAuthHeaders ? authStore.getAuthHeaders() : {};
    const res = await clientAPI().get(
      `${apiBase.replace(/\/api\/?$/, "")}/api/admin/reports?months=${m}`,
      { headers }
    );
    const data = res.data ?? res;

    // Nếu API trả object thì dùng, nếu không thì giữ rỗng
    if (data && typeof data === "object") {
      labels.value = Array.isArray(data.monthly?.labels)
        ? data.monthly.labels
        : [];
      thisYear.value = Array.isArray(data.monthly?.thisYear)
        ? data.monthly.thisYear.map(Number)
        : [];
      lastYear.value = Array.isArray(data.monthly?.lastYear)
        ? data.monthly.lastYear.map(Number)
        : [];
      topProducts.value = Array.isArray(data.topProducts)
        ? data.topProducts.map((p: any) => ({
            id: p.id,
            name: p.name ?? `#${p.id ?? ""}`,
            sold: Number(p.sold ?? 0),
            revenue: Number(p.revenue ?? 0),
            imageUrl: p.imageUrl ?? null,
          }))
        : [];

      summary.value = {
        totalRevenue: Number(
          data.summary?.totalRevenue ??
            thisYear.value.reduce((a, b) => a + b, 0)
        ),
        totalOrders: Number(data.summary?.totalOrders ?? 0),
        avgOrderValue: Number(data.summary?.avgOrderValue ?? 0),
      };

      dataSourceLabel.value = "Dữ liệu từ API";
    } else {
      // nếu API không trả đúng object -> set rỗng
      labels.value = [];
      thisYear.value = [];
      lastYear.value = [];
      topProducts.value = [];
      summary.value = { totalRevenue: 0, totalOrders: 0, avgOrderValue: 0 };
      dataSourceLabel.value = "Không có dữ liệu";
    }
  } catch (err) {
    console.warn("fetchReport error", err);
    // Khi lỗi gọi API: set dữ liệu rỗng để UI hiển thị "Không có dữ liệu"
    labels.value = [];
    thisYear.value = [];
    lastYear.value = [];
    topProducts.value = [];
    summary.value = { totalRevenue: 0, totalOrders: 0, avgOrderValue: 0 };
    dataSourceLabel.value = "Lỗi khi lấy dữ liệu";
  } finally {
    loading.value = false;
  }
}

// ---------- SVG helper functions ----------
function pointsFromArray(arr: number[]) {
  const n = arr.length || 1;
  const w = LINE_W - padding * 2;
  const max = Math.max(...arr, 1);
  const min = 0;
  const range = Math.max(1, max - min);
  return arr.map((v, i) => {
    const x = padding + (i / Math.max(1, n - 1)) * w;
    const y = padTop + (1 - (v - min) / range) * (LINE_H - padTop - padBottom);
    return { x, y, v };
  });
}
const thisYearPoints = computed(() => pointsFromArray(thisYear.value));
const lastYearPoints = computed(() => pointsFromArray(lastYear.value));

function xForIndex(i: number) {
  const n = labels.value.length || 1;
  const w = LINE_W - padding * 2;
  return padding + (i / Math.max(1, n - 1)) * w;
}
function linePath(points: { x: number; y: number }[]) {
  if (!points.length) return "";
  return points
    .map((p, i) => `${i === 0 ? "M" : "L"} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`)
    .join(" ");
}
function areaPath(points: { x: number; y: number; v?: number }[]) {
  if (!points.length) return "";
  const top = points
    .map((p, i) => `${i === 0 ? "M" : "L"} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`)
    .join(" ");
  const last = points[points.length - 1];
  const first = points[0];
  const baseY = LINE_H - padBottom;
  return `${top} L ${last.x.toFixed(2)} ${baseY} L ${first.x.toFixed(
    2
  )} ${baseY} Z`;
}

/** =========================
 * Top products helpers
 * ========================= */
const topProductsDisplay = computed(() => topProducts.value.slice(0, 8));
const maxSold = computed(() =>
  Math.max(1, ...topProductsDisplay.value.map((p) => p.sold))
);

// CSV export
function exportCSV() {
  const rows = topProducts.value.map((p, idx) => [
    idx + 1,
    p.name,
    p.sold,
    p.revenue,
  ]);
  const headers = ["#", "Sản phẩm", "Số lượng", "Doanh thu"];
  const csv = [headers, ...rows]
    .map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(","))
    .join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `top-products-${new Date().toISOString().slice(0, 10)}.csv`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/** =========================
 * Tooltip (absolute) for SVG & bars
 * ========================= */
const tooltip = ref({
  visible: false,
  x: 0,
  y: 0,
  label: "",
  value: 0,
  note: "",
});

function hideTooltip() {
  tooltip.value.visible = false;
}
function showPointTooltip(
  p: { x: number; y: number; v?: number },
  idx: number,
  which: "this" | "last"
) {
  const rect = (
    document.querySelector('[ref="lineWrapper"]') as HTMLElement
  )?.getBoundingClientRect();
  tooltip.value = {
    visible: true,
    x: p.x + 10,
    y: p.y - 10,
    label: labels.value[idx] ?? "",
    value: Math.round(Number(p.v ?? 0)),
    note: which === "this" ? "Năm nay" : "Năm trước",
  };
}
function showBarTooltip(ev: MouseEvent, prod: TopProduct) {
  const target = ev.currentTarget as HTMLElement;
  const rect = target.getBoundingClientRect();
  tooltip.value = {
    visible: true,
    x: rect.right - 100,
    y: rect.top - 8,
    label: prod.name,
    value: prod.sold,
    note: `Doanh thu: ${formatCurrency(prod.revenue)}`,
  };
}

/** =========================
 * Actions / lifecycle
 * ========================= */
function refresh() {
  fetchReport(months.value);
}

onMounted(() => {
  fetchReport(months.value);
});

watch(months, (v) => {
  fetchReport(v);
});

const tooltipStyle = computed(() => {
  return {
    position: "absolute",
    left: `${tooltip.value.x}px`,
    top: `${tooltip.value.y}px`,
    transform: "translate(-50%, -100%)",
  };
});
</script>

<style scoped>
svg {
  display: block;
  width: 100%;
  height: 100%;
}
/* tooltip absolute positioning */
[ref="lineWrapper"] > div[style] {
  position: absolute;
}
/* small styling */
.bg-yellow-400 {
  background-color: #fde68a;
}
select {
  min-width: 140px;
}
</style>
