// apps/frontend-next/src/app/(customer)/account/orders/page.tsx
// ===== TMFashion Account Orders Page =====
// Tương đương pages/account/orders.vue
// SD: Quản lý đơn hàng → User xem lịch sử đơn hàng
// STM Người dùng mua hàng: Xem đơn hàng → Lọc trạng thái → Xem chi tiết → Hủy đơn

"use client";

import { useEffect, useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useAuthStore } from "@/stores/auth";
import { api } from "@/lib/api";
import { formatVNDWithComma, formatDate } from "@/utils";

interface OrderItem {
  product_id?: { _id: string; name: string; image_url?: string };
  quantity: number;
  price: number;
}

interface Order {
  _id: string;
  items?: OrderItem[];
  total_amount: number;
  status: string;
  payment_method?: string;
  payment_status?: string;
  shipping_address?: string;
  created_at: string;
}

const STATUS_TABS = [
  { key: "", label: "Tất cả" },
  { key: "pending", label: "Chờ xử lý" },
  { key: "confirmed", label: "Đã xác nhận" },
  { key: "shipping", label: "Đang giao" },
  { key: "delivered", label: "Hoàn thành" },
  { key: "cancelled", label: "Đã hủy" },
];

const STATUS_COLORS: Record<string, string> = {
  pending: "bg-yellow-100 text-yellow-700",
  confirmed: "bg-blue-100 text-blue-700",
  shipping: "bg-indigo-100 text-indigo-700",
  completed: "bg-green-100 text-green-700",
  delivered: "bg-green-100 text-green-700",
  cancelled: "bg-red-100 text-red-700",
};

export default function AccountOrdersPage() {
  const router = useRouter();
  const { isLoggedIn } = useAuthStore();
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeStatus, setActiveStatus] = useState("");
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [orderDetails, setOrderDetails] = useState<Record<string, OrderItem[]>>({});

  const fetchOrders = useCallback(async () => {
    setLoading(true);
    try {
      const data = await api.get<{ orders: Order[] }>("/orders");
      setOrders(data.orders || []);
    } catch {
      /* ignore */
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!isLoggedIn) {
      router.push("/login");
      return;
    }
    fetchOrders();
  }, [isLoggedIn, router, fetchOrders]);

  const filteredOrders = activeStatus
    ? orders.filter((o) => o.status === activeStatus)
    : orders;

  async function cancelOrder(orderId: string) {
    if (!confirm("Bạn có chắc muốn hủy đơn hàng này?")) return;
    try {
      await api.put(`/orders/${orderId}/cancel`);
      fetchOrders();
    } catch (err: unknown) {
      alert(err instanceof Error ? err.message : "Lỗi hủy đơn");
    }
  }

  async function toggleExpand(orderId: string) {
    if (expandedId === orderId) {
      setExpandedId(null);
      return;
    }
    setExpandedId(orderId);
    // Fetch items if not already loaded
    if (!orderDetails[orderId]) {
      try {
        const data = await api.get<{ order: Order; items: OrderItem[] }>(`/orders/${orderId}`);
        setOrderDetails((prev) => ({ ...prev, [orderId]: data.items || [] }));
      } catch { /* ignore */ }
    }
  }

  return (
    <div className="max-w-[1200px] mx-auto px-4 py-8">
      <div className="grid md:grid-cols-[240px_1fr] gap-8">
        {/* Sidebar */}
        <aside className="space-y-2">
          <Link href="/account" className="block px-4 py-2 rounded-lg hover:bg-gray-100 text-gray-600 text-sm transition">
            Thông tin cá nhân
          </Link>
          <Link href="/account/orders" className="block px-4 py-2 rounded-lg bg-primary text-gray-800 font-medium text-sm">
            Đơn hàng của tôi
          </Link>
        </aside>

        {/* Main */}
        <div className="space-y-6">
          <h1 className="text-xl font-bold text-gray-800">Đơn hàng của tôi</h1>

          {/* Status Tabs */}
          <div className="flex flex-wrap gap-2">
            {STATUS_TABS.map((tab) => (
              <button
                key={tab.key}
                onClick={() => setActiveStatus(tab.key)}
                className={`px-4 py-2 rounded-lg text-sm font-medium transition ${
                  activeStatus === tab.key ? "bg-primary text-gray-800" : "bg-white border hover:bg-gray-50"
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>

          {/* Orders List */}
          {loading ? (
            <div className="text-center py-12 text-gray-400">Đang tải...</div>
          ) : filteredOrders.length === 0 ? (
            <div className="text-center py-12">
              <p className="text-gray-400 mb-4">Không có đơn hàng nào</p>
              <Link href="/shop" className="text-primary hover:underline">Tiếp tục mua sắm</Link>
            </div>
          ) : (
            <div className="space-y-4">
              {filteredOrders.map((order) => (
                <div key={order._id} className="bg-white rounded-lg shadow overflow-hidden">
                  {/* Order Header */}
                  <div
                    className="flex items-center justify-between px-6 py-4 cursor-pointer hover:bg-gray-50"
                    onClick={() => toggleExpand(order._id)}
                  >
                    <div className="flex items-center gap-4">
                      <div>
                        <p className="text-sm font-mono text-gray-500">#{order._id.slice(-8)}</p>
                        <p className="text-xs text-gray-400">{formatDate(order.created_at)}</p>
                      </div>
                      <span className={`px-2 py-1 rounded-full text-xs font-medium ${STATUS_COLORS[order.status] || "bg-gray-100"}`}>
                        {order.status}
                      </span>
                    </div>
                    <div className="text-right">
                      <p className="font-medium text-gray-800">{formatVNDWithComma(order.total_amount)}đ</p>
                      <p className="text-xs text-gray-400">{(order.items || orderDetails[order._id] || []).length} sản phẩm</p>
                    </div>
                  </div>

                  {/* Expanded Details */}
                  {expandedId === order._id && (
                    <div className="border-t px-6 py-4 space-y-4">
                      {/* Items */}
                      <div className="space-y-3">
                        {(orderDetails[order._id] || []).map((item, i) => (
                          <div key={i} className="flex items-center gap-4">
                            <img src={item.product_id?.image_url || "/placeholder.png"} alt="" className="w-14 h-14 rounded object-cover border" />
                            <div className="flex-1">
                              <p className="text-sm font-medium text-gray-800">{item.product_id?.name}</p>
                              <p className="text-xs text-gray-400">x{item.quantity} | {formatVNDWithComma(item.price)}đ</p>
                            </div>
                            <p className="text-sm font-medium">{formatVNDWithComma(item.price * item.quantity)}đ</p>
                          </div>
                        ))}
                      </div>

                      {/* Order Info */}
                      <div className="grid grid-cols-2 gap-2 text-sm pt-2 border-t">
                        <div>
                          <span className="text-gray-500">Thanh toán:</span>{" "}
                          <span className="font-medium">{order.payment_method || "COD"}</span>
                        </div>
                        {order.shipping_address && (
                          <div className="col-span-2">
                            <span className="text-gray-500">Giao đến:</span>{" "}
                            <span className="font-medium">{order.shipping_address}</span>
                          </div>
                        )}
                      </div>

                      {/* Cancel button */}
                      {order.status === "pending" && (
                        <div className="pt-2 border-t">
                          <button
                            onClick={() => cancelOrder(order._id)}
                            className="px-4 py-2 text-sm border border-red-200 text-red-500 rounded-lg hover:bg-red-50 transition"
                          >
                            Hủy đơn hàng
                          </button>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// frontend-nuxt/pages/account/orders.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Header -->
    <div class="bg-white shadow-sm">
      <div class="max-w-6xl mx-auto px-4 py-4">
        <div class="flex items-center gap-4">
          <NuxtLink to="/" class="text-2xl font-bold text-gray-800">TMF</NuxtLink>
          <span class="text-gray-300">|</span>
          <h1 class="text-xl text-gray-600">Lịch sử đơn hàng</h1>
        </div>
      </div>
    </div>

    <div class="max-w-6xl mx-auto px-4 py-8">
      <!-- Chưa đăng nhập -->
      <div v-if="!authStore.isLoggedIn" class="bg-white rounded-lg shadow p-8 text-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 mx-auto text-gray-300 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
        </svg>
        <p class="text-gray-500 mb-4">Vui lòng đăng nhập để xem lịch sử đơn hàng</p>
        <NuxtLink
          to="/login"
          class="inline-block px-6 py-3 bg-primary hover:bg-yellow-500 text-gray-800 font-medium rounded-lg transition"
        >
          Đăng nhập
        </NuxtLink>
      </div>

      <!-- Đã đăng nhập -->
      <div v-else class="grid lg:grid-cols-4 gap-6">
        <!-- Sidebar Menu -->
        <div class="lg:col-span-1">
          <div class="bg-white rounded-lg shadow p-4">
            <!-- User info -->
            <div class="flex items-center gap-3 pb-4 border-b mb-4">
              <div class="w-12 h-12 bg-primary rounded-full flex items-center justify-center">
                <span class="text-xl font-bold text-gray-800">
                  {{ userInitial }}
                </span>
              </div>
              <div>
                <p class="font-medium text-gray-800">{{ authStore.user?.fullName || 'Khách hàng' }}</p>
                <p class="text-sm text-gray-500">{{ authStore.user?.email }}</p>
              </div>
            </div>

            <!-- Menu -->
            <nav class="space-y-1">
              <NuxtLink
                to="/account"
                class="flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 hover:bg-gray-100 transition"
              >
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                </svg>
                Thông tin cá nhân
              </NuxtLink>

              <NuxtLink
                to="/account/orders"
                class="flex items-center gap-3 px-3 py-2 rounded-lg bg-yellow-50 text-yellow-700"
              >
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                </svg>
                Lịch sử đơn hàng
              </NuxtLink>

              <button
                class="flex items-center gap-3 px-3 py-2 rounded-lg text-red-600 hover:bg-red-50 transition w-full"
                @click="handleLogout"
              >
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                </svg>
                Đăng xuất
              </button>
            </nav>
          </div>
        </div>

        <!-- Main Content -->
        <div class="lg:col-span-3">
          <div class="bg-white rounded-lg shadow">
            <!-- Header -->
            <div class="p-6 border-b">
              <h2 class="text-xl font-bold text-gray-800">Lịch sử đơn hàng</h2>
              <p class="text-gray-500 mt-1">Theo dõi trạng thái các đơn hàng của bạn</p>
            </div>

            <!-- Filter tabs -->
            <div class="border-b">
              <div class="flex overflow-x-auto">
                <button
                  v-for="tab in statusTabs"
                  :key="tab.value"
                  class="px-6 py-3 text-sm font-medium whitespace-nowrap border-b-2 transition"
                  :class="activeStatus === tab.value 
                    ? 'border-yellow-500 text-yellow-600' 
                    : 'border-transparent text-gray-500 hover:text-gray-700'"
                  @click="activeStatus = tab.value"
                >
                  {{ tab.label }}
                  <span 
                    v-if="getOrderCountByStatus(tab.value) > 0"
                    class="ml-1.5 px-2 py-0.5 text-xs rounded-full"
                    :class="activeStatus === tab.value ? 'bg-yellow-100 text-yellow-700' : 'bg-gray-100 text-gray-600'"
                  >
                    {{ getOrderCountByStatus(tab.value) }}
                  </span>
                </button>
              </div>
            </div>

            <!-- Loading -->
            <div v-if="loading" class="p-8 text-center">
              <svg class="animate-spin h-8 w-8 mx-auto text-yellow-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              <p class="text-gray-500 mt-2">Đang tải...</p>
            </div>

            <!-- Empty state -->
            <div v-else-if="filteredOrders.length === 0" class="p-8 text-center">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 mx-auto text-gray-300 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
              </svg>
              <p class="text-gray-500 mb-4">
                {{ activeStatus === 'ALL' ? 'Bạn chưa có đơn hàng nào' : 'Không có đơn hàng nào' }}
              </p>
              <NuxtLink
                to="/category/ao"
                class="inline-block px-6 py-3 bg-primary hover:bg-yellow-500 text-gray-800 font-medium rounded-lg transition"
              >
                Mua sắm ngay
              </NuxtLink>
            </div>

            <!-- Orders list -->
            <div v-else class="divide-y">
              <div
                v-for="order in filteredOrders"
                :key="order.id"
                class="p-6"
              >
                <!-- Order header -->
                <div class="flex flex-wrap items-center justify-between gap-4 mb-4">
                  <div>
                    <p class="text-sm text-gray-500">
                      Mã đơn hàng: 
                      <span class="font-medium text-gray-800">TMF{{ String(order.id).padStart(8, '0') }}</span>
                    </p>
                    <p class="text-sm text-gray-500">
                      Ngày đặt: {{ formatDate(order.createdAt) }}
                    </p>
                  </div>
                  <span 
                    class="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium"
                    :class="getStatusClass(order.status)"
                  >
                    <span class="w-2 h-2 rounded-full mr-2" :class="getStatusDotClass(order.status)"></span>
                    {{ getStatusLabel(order.status) }}
                  </span>
                </div>

                <!-- Order items -->
                <div class="space-y-3 mb-4">
                  <div
                    v-for="item in order.items"
                    :key="item.id"
                    class="flex gap-4"
                  >
                    <img
                      :src="item.product?.imageUrl || '/placeholder.png'"
                      :alt="item.product?.name"
                      class="w-16 h-16 object-cover rounded-lg border"
                    />
                    <div class="flex-1 min-w-0">
                      <p class="font-medium text-gray-800 truncate">{{ item.product?.name }}</p>
                      <p class="text-sm text-gray-500">
                        {{ formatVNDWithComma(item.price) }}đ x {{ item.quantity }}
                      </p>
                    </div>
                    <div class="text-right">
                      <p class="font-medium text-gray-800">
                        {{ formatVNDWithComma(item.price * item.quantity) }}đ
                      </p>
                    </div>
                  </div>
                </div>

                <!-- Order footer -->
                <div class="flex flex-wrap items-center justify-between gap-4 pt-4 border-t">
                  <div class="text-sm text-gray-500">
                    {{ order.items.length }} sản phẩm
                  </div>
                  <div class="text-right">
                    <p class="text-sm text-gray-500">Tổng tiền:</p>
                    <p class="text-lg font-bold text-red-500">
                      {{ formatVNDWithComma(order.totalAmount) }}đ
                    </p>
                  </div>
                </div>

                <!-- Shipping info -->
                <div v-if="order.shippingAddress" class="mt-4 p-3 bg-gray-50 rounded-lg text-sm">
                  <p class="text-gray-600">
                    <span class="font-medium">Địa chỉ:</span> {{ order.shippingAddress }}
                  </p>
                  <p v-if="order.phone" class="text-gray-600 mt-1">
                    <span class="font-medium">SĐT:</span> {{ order.phone }}
                  </p>
                  <p v-if="order.note" class="text-gray-600 mt-1">
                    <span class="font-medium">Ghi chú:</span> {{ order.note }}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useAuthStore } from '~/store/auth'
import clientAPI from '~/services/_AxiosConfig'

interface OrderItem {
  id: number
  quantity: number
  price: number
  product: {
    id: number
    name: string
    imageUrl: string | null
  } | null
}

interface Order {
  id: number
  status: string
  totalAmount: number
  shippingAddress: string | null
  phone: string | null
  note: string | null
  createdAt: string
  items: OrderItem[]
}

const authStore = useAuthStore()
const router = useRouter()

const orders = ref<Order[]>([])
const loading = ref(false)
const activeStatus = ref('ALL')

const statusTabs = [
  { label: 'Tất cả', value: 'ALL' },
  { label: 'Chờ xác nhận', value: 'PENDING' },
  { label: 'Đã xác nhận', value: 'CONFIRMED' },
  { label: 'Đang giao', value: 'SHIPPING' },
  { label: 'Đã giao', value: 'COMPLETED' },
  { label: 'Đã hủy', value: 'CANCELLED' },
]

const userInitial = computed(() => {
  const name = authStore.user?.fullName || authStore.user?.email || 'U'
  return name.charAt(0).toUpperCase()
})

const filteredOrders = computed(() => {
  if (activeStatus.value === 'ALL') {
    return orders.value
  }
  return orders.value.filter(order => order.status === activeStatus.value)
})

function getOrderCountByStatus(status: string) {
  if (status === 'ALL') {
    return orders.value.length
  }
  return orders.value.filter(order => order.status === status).length
}

function getStatusLabel(status: string) {
  const labels: Record<string, string> = {
    PENDING: 'Chờ xác nhận',
    CONFIRMED: 'Đã xác nhận',
    SHIPPING: 'Đang giao hàng',
    COMPLETED: 'Đã giao',
    CANCELLED: 'Đã hủy',
  }
  return labels[status] || status
}

function getStatusClass(status: string) {
  const classes: Record<string, string> = {
    PENDING: 'bg-yellow-100 text-yellow-800',
    CONFIRMED: 'bg-blue-100 text-blue-800',
    SHIPPING: 'bg-purple-100 text-purple-800',
    COMPLETED: 'bg-green-100 text-green-800',
    CANCELLED: 'bg-red-100 text-red-800',
  }
  return classes[status] || 'bg-gray-100 text-gray-800'
}

function getStatusDotClass(status: string) {
  const classes: Record<string, string> = {
    PENDING: 'bg-yellow-500',
    CONFIRMED: 'bg-blue-500',
    SHIPPING: 'bg-purple-500',
    COMPLETED: 'bg-green-500',
    CANCELLED: 'bg-red-500',
  }
  return classes[status] || 'bg-gray-500'
}

function formatDate(dateString: string) {
  const date = new Date(dateString)
  return date.toLocaleDateString('vi-VN', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

async function fetchOrders() {
  if (!authStore.isLoggedIn) return

  loading.value = true
  try {
    const response = await clientAPI().get('/orders', {
      headers: authStore.getAuthHeaders(),
    })
    orders.value = response.data.orders || []
  } catch (err: any) {
    console.error('Fetch orders error:', err)
  } finally {
    loading.value = false
  }
}

function handleLogout() {
  authStore.logout()
  router.push('/')
}

onMounted(() => {
  fetchOrders()
})
</script>
