// apps/frontend-next/src/app/login/page.tsx
// ===== TMFashion Login Page =====
// Tương đương pages/login.vue
// STM Đăng nhập: Nhập email/password → Validate → Gửi API → Thành công/Thất bại

"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useEffect } from "react";
import { useAuthStore } from "@/stores/auth";

export default function LoginPage() {
  const router = useRouter();
  const { login, isLoggedIn, isAdmin, loading, error, setError } = useAuthStore();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  // Redirect nếu đã đăng nhập
  useEffect(() => {
    if (isLoggedIn) {
      router.push(isAdmin ? "/admin" : "/");
    }
  }, [isLoggedIn, isAdmin, router]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");

    if (!email || !password) {
      setError("Vui lòng nhập email và mật khẩu");
      return;
    }

    try {
      await login(email, password);
      // Redirect happens via useEffect above
    } catch {
      // Error đã được set trong store
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center px-4">
      <div className="w-full max-w-md">
        {/* Logo */}
        <div className="text-center mb-8">
          <Link href="/" className="inline-block">
            <h1 className="text-4xl font-bold text-primary">TMF</h1>
            <p className="text-sm text-gray-500 mt-1">TMFashion</p>
          </Link>
        </div>

        {/* Login Form */}
        <div className="bg-white rounded-lg shadow-lg p-8">
          <h2 className="text-2xl font-bold text-gray-800 mb-6 text-center">
            Đăng nhập
          </h2>

          {/* Error Alert */}
          {error && (
            <div className="mb-4 p-3 bg-red-50 border border-red-200 text-red-600 rounded-lg text-sm">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Email
              </label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="your@email.com"
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Mật khẩu
              </label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="••••••••"
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
                required
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full py-3 bg-primary hover:bg-yellow-400 text-gray-800 font-bold rounded-lg transition disabled:opacity-50"
            >
              {loading ? "Đang đăng nhập..." : "Đăng nhập"}
            </button>
          </form>

          <div className="mt-6 text-center">
            <p className="text-sm text-gray-500">
              Chưa có tài khoản?{" "}
              <Link
                href="/register"
                className="text-primary hover:underline font-medium"
              >
                Đăng ký ngay
              </Link>
            </p>
          </div>
        </div>

        {/* Demo Credentials */}
        <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4 text-sm">
          <p className="font-semibold text-blue-800 mb-2">
            Demo Credentials:
          </p>
          <p className="text-blue-700">
            Admin: admin@tmfashion.vn / admin123
          </p>
          <p className="text-blue-700">
            Customer: minh@gmail.com / 123456
          </p>
        </div>
      </div>
    </div>
  );
}

// frontend-nuxt/pages/login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-100">
    <div class="max-w-md w-full bg-white rounded-lg shadow-lg p-8">
      <!-- Logo -->
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-800">TMF</h1>
        <p class="text-gray-500 mt-2">Đăng nhập vào tài khoản</p>
      </div>

      <!-- Error Alert -->
      <div
        v-if="error"
        class="mb-4 p-4 bg-red-50 border border-red-200 rounded-lg text-red-600 text-sm"
      >
        {{ error }}
      </div>

      <!-- Login Form -->
      <form @submit.prevent="handleLogin">
        <!-- Email -->
        <div class="mb-4">
          <label class="block text-gray-700 text-sm font-medium mb-2" for="email">
            Email
          </label>
          <input
            id="email"
            v-model="email"
            type="email"
            placeholder="your@email.com"
            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-yellow-400 focus:border-transparent transition"
            required
          />
        </div>

        <!-- Password -->
        <div class="mb-6">
          <label class="block text-gray-700 text-sm font-medium mb-2" for="password">
            Mật khẩu
          </label>
          <input
            id="password"
            v-model="password"
            type="password"
            placeholder="••••••••"
            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-yellow-400 focus:border-transparent transition"
            required
          />
        </div>

        <!-- Submit Button -->
        <button
          type="submit"
          :disabled="loading"
          class="w-full bg-yellow-400 hover:bg-yellow-500 text-gray-800 font-semibold py-3 px-4 rounded-lg transition duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <span v-if="loading">Đang đăng nhập...</span>
          <span v-else>Đăng nhập</span>
        </button>
      </form>

      <!-- Back to Home -->
      <div class="mt-6 text-center">
        <NuxtLink
          to="/"
          class="text-gray-500 hover:text-gray-700 text-sm"
        >
          ← Quay lại trang chủ
        </NuxtLink>
      </div>

      <!-- Register Link -->
      <div class="mt-4 text-center">
        <p class="text-gray-600 text-sm">
          Chưa có tài khoản?
          <NuxtLink to="/register" class="text-blue-600 hover:underline font-medium">
            Đăng ký ngay
          </NuxtLink>
        </p>
      </div>

      <!-- Demo Credentials (dev only) -->
      <div class="mt-8 p-4 bg-gray-50 rounded-lg text-sm text-gray-600">
        <p class="font-medium mb-2">Tài khoản demo:</p>
        <p>Email: <code class="bg-gray-200 px-1 rounded">admin@tmfashion.com</code></p>
        <p>Password: <code class="bg-gray-200 px-1 rounded">123456</code></p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useAuthStore } from '~/store/auth'

const authStore = useAuthStore()
const router = useRouter()

const email = ref('')
const password = ref('')
const error = ref('')
const loading = computed(() => authStore.loading)

// Nếu đã login rồi, redirect
onMounted(() => {
  if (authStore.isLoggedIn) {
    if (authStore.isAdmin) {
      router.push('/admin')
    } else {
      router.push('/')
    }
  }
})

async function handleLogin() {
  error.value = ''

  const result = await authStore.login(email.value, password.value)

  if (result.success) {
    // Redirect dựa vào role
    if (authStore.isAdmin) {
      router.push('/admin')
    } else {
      router.push('/')
    }
  } else {
    error.value = result.error || 'Đăng nhập thất bại'
  }
}
</script>
