// frontend-nuxt/pages/admin/products/index.vue
<template>
  <div>
    <div class="flex items-center justify-between mb-6">
      <h1 class="text-2xl font-bold text-gray-800">Quản lý sản phẩm</h1>
      <NuxtLink
        to="/admin/products/create"
        class="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition flex items-center gap-2"
      >
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
        </svg>
        Thêm sản phẩm
      </NuxtLink>
    </div>

    <!-- Search & Filter -->
    <div class="bg-white rounded-lg shadow p-4 mb-6">
      <div class="flex flex-wrap gap-4">
        <div class="flex-1 min-w-[200px]">
          <input
            v-model="search"
            type="text"
            placeholder="Tìm theo tên hoặc SKU..."
            class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-yellow-400"
            @input="debouncedSearch"
          />
        </div>
        <select
          v-model="filterCategory"
          class="px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-yellow-400"
          @change="fetchProducts"
        >
          <option value="">Tất cả danh mục</option>
          <option v-for="cat in categories" :key="cat.id" :value="cat.id">
            {{ cat.name }}
          </option>
        </select>
        <select
          v-model="filterStatus"
          class="px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-yellow-400"
          @change="fetchProducts"
        >
          <option value="">Tất cả trạng thái</option>
          <option value="true">Đang bán</option>
          <option value="false">Ngừng bán</option>
        </select>
      </div>
    </div>

    <!-- Products Table -->
    <div class="bg-white rounded-lg shadow overflow-hidden">
      <!-- Loading -->
      <div v-if="loading" class="flex items-center justify-center py-12">
        <svg class="animate-spin h-8 w-8 text-yellow-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
      </div>

      <table v-else class="w-full">
        <thead class="bg-gray-50 border-b">
          <tr>
            <th class="text-left px-6 py-4 text-sm font-semibold text-gray-600">Sản phẩm</th>
            <th class="text-left px-6 py-4 text-sm font-semibold text-gray-600">SKU</th>
            <th class="text-left px-6 py-4 text-sm font-semibold text-gray-600">Danh mục</th>
            <th class="text-right px-6 py-4 text-sm font-semibold text-gray-600">Giá</th>
            <th class="text-center px-6 py-4 text-sm font-semibold text-gray-600">Trạng thái</th>
            <th class="text-center px-6 py-4 text-sm font-semibold text-gray-600">Thao tác</th>
          </tr>
        </thead>
        <tbody class="divide-y">
          <tr v-for="product in products" :key="product.id" class="hover:bg-gray-50">
            <td class="px-6 py-4">
              <div class="flex items-center gap-3">
                <img
                  :src="product.imageUrl || '/placeholder.png'"
                  :alt="product.name"
                  class="w-12 h-12 object-cover rounded-lg border"
                />
                <div>
                  <p class="font-medium text-gray-800 line-clamp-1">{{ product.name }}</p>
                  <p class="text-sm text-gray-500">{{ product.brand?.name }}</p>
                </div>
              </div>
            </td>
            <td class="px-6 py-4 text-gray-600">{{ product.sku }}</td>
            <td class="px-6 py-4 text-gray-600">{{ product.category?.name }}</td>
            <td class="px-6 py-4 text-right">
              <p class="font-medium text-gray-800">{{ formatVNDWithComma(product.price) }}đ</p>
              <p v-if="product.compareAtPrice" class="text-sm text-gray-400 line-through">
                {{ formatVNDWithComma(product.compareAtPrice) }}đ
              </p>
            </td>
            <td class="px-6 py-4 text-center">
              <span 
                class="px-2 py-1 rounded-full text-xs font-medium"
                :class="product.isActive ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'"
              >
                {{ product.isActive ? 'Đang bán' : 'Ngừng bán' }}
              </span>
            </td>
            <td class="px-6 py-4">
              <div class="flex items-center justify-center gap-2">
                <NuxtLink
                  :to="`/admin/products/${product.id}`"
                  class="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition"
                  title="Chỉnh sửa"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                  </svg>
                </NuxtLink>
                <button
                  class="p-2 text-yellow-600 hover:bg-yellow-50 rounded-lg transition"
                  :title="product.isActive ? 'Ẩn sản phẩm' : 'Hiện sản phẩm'"
                  @click="toggleStatus(product)"
                >
                  <svg v-if="product.isActive" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
                  </svg>
                  <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                  </svg>
                </button>
                <button
                  class="p-2 text-red-600 hover:bg-red-50 rounded-lg transition"
                  title="Xóa"
                  @click="deleteProduct(product)"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                </button>
              </div>
            </td>
          </tr>
          <tr v-if="products.length === 0">
            <td colspan="6" class="px-6 py-12 text-center text-gray-500">
              Không có sản phẩm nào
            </td>
          </tr>
        </tbody>
      </table>

      <!-- Pagination -->
      <div v-if="pagination.totalPages > 1" class="px-6 py-4 border-t flex items-center justify-between">
        <p class="text-sm text-gray-600">
          Hiển thị {{ (pagination.page - 1) * pagination.limit + 1 }} - 
          {{ Math.min(pagination.page * pagination.limit, pagination.total) }} 
          trong {{ pagination.total }} sản phẩm
        </p>
        <div class="flex gap-2">
          <button
            :disabled="pagination.page <= 1"
            class="px-3 py-1 border rounded hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed"
            @click="goToPage(pagination.page - 1)"
          >
            Trước
          </button>
          <button
            v-for="p in visiblePages"
            :key="p"
            class="px-3 py-1 border rounded"
            :class="p === pagination.page ? 'bg-yellow-500 text-white border-yellow-500' : 'hover:bg-gray-100'"
            @click="goToPage(p)"
          >
            {{ p }}
          </button>
          <button
            :disabled="pagination.page >= pagination.totalPages"
            class="px-3 py-1 border rounded hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed"
            @click="goToPage(pagination.page + 1)"
          >
            Sau
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useAuthStore } from '~/store/auth'
import clientAPI from '~/services/_AxiosConfig'

definePageMeta({
  layout: 'admin',
  middleware: 'admin',
})

const authStore = useAuthStore()
const config = useRuntimeConfig()

interface Product {
  id: number
  name: string
  sku: string
  price: number
  compareAtPrice: number | null
  imageUrl: string | null
  isActive: boolean
  category?: { id: number; name: string }
  brand?: { id: number; name: string }
}

interface Category {
  id: number
  name: string
}

const loading = ref(false)
const products = ref<Product[]>([])
const categories = ref<Category[]>([])
const search = ref('')
const filterCategory = ref('')
const filterStatus = ref('')
const pagination = ref({
  page: 1,
  limit: 20,
  total: 0,
  totalPages: 0,
})

let searchTimeout: ReturnType<typeof setTimeout> | null = null

const visiblePages = computed(() => {
  const pages: number[] = []
  const current = pagination.value.page
  const total = pagination.value.totalPages
  
  for (let i = Math.max(1, current - 2); i <= Math.min(total, current + 2); i++) {
    pages.push(i)
  }
  return pages
})

function debouncedSearch() {
  if (searchTimeout) clearTimeout(searchTimeout)
  searchTimeout = setTimeout(() => {
    pagination.value.page = 1
    fetchProducts()
  }, 300)
}

async function fetchCategories() {
  try {
    const response = await $fetch<Category[]>(`${config.public.apiBase}/categories`)
    categories.value = response
  } catch (err) {
    console.error('Fetch categories error:', err)
  }
}

async function fetchProducts() {
  loading.value = true
  try {
    const params = new URLSearchParams()
    params.append('page', String(pagination.value.page))
    params.append('limit', String(pagination.value.limit))
    
    if (search.value) params.append('search', search.value)
    if (filterCategory.value) params.append('categoryId', filterCategory.value)
    if (filterStatus.value) params.append('isActive', filterStatus.value)

    const response = await clientAPI().get(`/products?${params.toString()}`)
    products.value = response.data.items || []
    
    if (response.data.pagination) {
      pagination.value = response.data.pagination
    }
  } catch (err) {
    console.error('Fetch products error:', err)
  } finally {
    loading.value = false
  }
}

async function toggleStatus(product: Product) {
  try {
    await clientAPI().put(
      `/products/${product.id}`,
      { isActive: !product.isActive },
      { headers: authStore.getAuthHeaders() }
    )
    product.isActive = !product.isActive
  } catch (err) {
    console.error('Toggle status error:', err)
    alert('Lỗi cập nhật trạng thái')
  }
}

async function deleteProduct(product: Product) {
  if (!confirm(`Bạn có chắc muốn xóa sản phẩm "${product.name}"?`)) return
  
  try {
    await clientAPI().delete(`/products/${product.id}`, {
      headers: authStore.getAuthHeaders(),
    })
    fetchProducts()
  } catch (err) {
    console.error('Delete product error:', err)
    alert('Lỗi xóa sản phẩm')
  }
}

function goToPage(page: number) {
  pagination.value.page = page
  fetchProducts()
}

onMounted(() => {
  fetchCategories()
  fetchProducts()
})
</script>

// apps/frontend-next/src/app/admin/products/page.tsx
// ===== TMFashion Admin Products Page =====
// Tương đương pages/admin/products/index.vue
// SD: Quản lý sản phẩm → Admin CRUD sản phẩm
// STM Quản lý sản phẩm: Xem danh sách → Tìm kiếm/Lọc → Thêm/Sửa/Xóa

"use client";

import { useEffect, useState, useCallback } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import { formatVNDWithComma } from "@/utils";
import type { Product } from "@/stores/product";
import type { Category } from "@/stores/category";

export default function AdminProductsPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [filterCategory, setFilterCategory] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  const fetchProducts = useCallback(async () => {
    setLoading(true);
    try {
      const params: Record<string, string | number | undefined> = {
        page: currentPage,
        limit: 15,
      };
      if (search) params.keyword = search;
      if (filterCategory) params.category_id = filterCategory;

      const data = await api.get<{ data: Product[]; pagination: { page: number; limit: number; total: number; totalPages: number } }>("/products", params);
      setProducts(data.data || []);
      setTotalPages(data.pagination?.totalPages || 1);
    } catch {
      /* ignore */
    } finally {
      setLoading(false);
    }
  }, [currentPage, search, filterCategory]);

  useEffect(() => {
    api.get<{ data: Category[] }>("/categories").then((res) => {
      const cats = Array.isArray(res) ? res : (res.data || []);
      setCategories(cats);
    });
  }, []);

  useEffect(() => {
    fetchProducts();
  }, [fetchProducts]);

  async function handleDelete(id: string) {
    if (!confirm("Bạn có chắc muốn xóa sản phẩm này?")) return;
    try {
      await api.delete(`/products/${id}`);
      fetchProducts();
    } catch {
      alert("Lỗi xóa sản phẩm");
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-800">Quản lý sản phẩm</h1>
        <Link
          href="/admin/products/create"
          className="px-4 py-2 bg-primary hover:bg-yellow-400 text-gray-800 font-medium rounded-lg transition"
        >
          + Thêm sản phẩm
        </Link>
      </div>

      {/* Filters */}
      <div className="bg-white rounded-lg shadow p-4 flex flex-col md:flex-row gap-4">
        <input
          type="text"
          placeholder="Tìm kiếm sản phẩm..."
          value={search}
          onChange={(e) => { setSearch(e.target.value); setCurrentPage(1); }}
          className="flex-1 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
        />
        <select
          value={filterCategory}
          onChange={(e) => { setFilterCategory(e.target.value); setCurrentPage(1); }}
          className="px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-primary"
        >
          <option value="">Tất cả danh mục</option>
          {categories.map((c) => (
            <option key={c._id} value={c._id}>{c.name}</option>
          ))}
        </select>
      </div>

      {/* Table */}
      <div className="bg-white rounded-lg shadow overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr className="text-sm text-gray-500">
                <th className="text-left py-3 px-4">Sản phẩm</th>
                <th className="text-left py-3 px-4">SKU</th>
                <th className="text-right py-3 px-4">Giá</th>
                <th className="text-center py-3 px-4">Danh mục</th>
                <th className="text-center py-3 px-4">Trạng thái</th>
                <th className="text-center py-3 px-4">Thao tác</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {loading ? (
                <tr>
                  <td colSpan={6} className="py-12 text-center text-gray-400">
                    Đang tải...
                  </td>
                </tr>
              ) : products.length === 0 ? (
                <tr>
                  <td colSpan={6} className="py-12 text-center text-gray-400">
                    Không tìm thấy sản phẩm
                  </td>
                </tr>
              ) : (
                products.map((p) => (
                  <tr key={p._id} className="hover:bg-gray-50">
                    <td className="py-3 px-4">
                      <div className="flex items-center gap-3">
                        <img
                          src={p.image_url || "/placeholder.png"}
                          alt={p.name}
                          className="w-12 h-12 rounded-lg object-cover border"
                        />
                        <span className="font-medium text-gray-800 line-clamp-1">
                          {p.name}
                        </span>
                      </div>
                    </td>
                    <td className="py-3 px-4 text-sm text-gray-500 font-mono">
                      {p.sku || "-"}
                    </td>
                    <td className="py-3 px-4 text-right">
                      <p className="font-medium text-gray-800">
                        {formatVNDWithComma(p.price)}đ
                      </p>
                      {p.compare_at_price && p.compare_at_price > p.price && (
                        <p className="text-xs text-gray-400 line-through">
                          {formatVNDWithComma(p.compare_at_price)}đ
                        </p>
                      )}
                    </td>
                    <td className="py-3 px-4 text-center text-sm">
                      {(p.category_id?.name || p.category?.name) || "-"}
                    </td>
                    <td className="py-3 px-4 text-center">
                      <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                        p.is_active !== false ? "bg-green-100 text-green-700" : "bg-gray-100 text-gray-500"
                      }`}>
                        {p.is_active !== false ? "Đang bán" : "Ẩn"}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-center">
                      <div className="flex items-center justify-center gap-2">
                        <Link
                          href={`/admin/products/${p._id}`}
                          className="px-3 py-1 text-sm border rounded hover:bg-gray-100 transition"
                        >
                          Sửa
                        </Link>
                        <button
                          onClick={() => handleDelete(p._id)}
                          className="px-3 py-1 text-sm border border-red-200 text-red-500 rounded hover:bg-red-50 transition"
                        >
                          Xóa
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="flex justify-center gap-2 p-4 border-t">
            {Array.from({ length: totalPages }, (_, i) => i + 1)
              .filter((p) => p === 1 || p === totalPages || Math.abs(p - currentPage) <= 2)
              .map((p) => (
                <button
                  key={p}
                  onClick={() => setCurrentPage(p)}
                  className={`px-3 py-1 rounded ${
                    p === currentPage ? "bg-primary text-gray-800 font-bold" : "hover:bg-gray-100"
                  }`}
                >
                  {p}
                </button>
              ))}
          </div>
        )}
      </div>
    </div>
  );
}
